### ISSUE TITLE
refactor how branch is generated

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1009]
1) We are applying the `executive` branch too broadly with the .gov websites. Instead of the [current logic](https://github.com/GSA/federal-website-index/blob/main/builder/main.py#L377), base domains should be compared against [this list](https://github.com/cisagov/dotgov-data/blob/main/current-federal.csv) and then applied. An example where this is an issue is websites from the uscourts source list.

**Comment by akuny** [comment]
The federal website index builder has been updated to correctly populate the "branch" field: https://github.com/GSA/federal-website-index/commit/1597e705827264b11b04a2c91a24cd4b420d6bb0

**Comment by gbinal** [comment]
great!  I'll validate then close this.  Thanks!
