### ISSUE TITLE
detecting og_type, og_image, og_url fields

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/site-scanning#1034]
for touchpoints.digital.gov the Site Scanning API is returning `null`

<img width="281" alt="ss5" src="https://github.com/GSA/site-scanning/assets/64987852/63c20b66-932b-493f-b605-26d92e56c927">

where the touchpoints.digital.gov html has values

<img width="423" alt="ss7" src="https://github.com/GSA/site-scanning/assets/64987852/4cbabf9e-bed5-4d29-9dc3-cf80fc3a3cc3">

**Comment by gbinal** [comment]
Will look into it.  Thanks!

**Comment by akuny** [comment]
Great catch: previously, the scanner was looking strictly for meta elements with a `property` attribute set to `og_image`, etc. We've updated the scanner to also look for meta elements with a `name` attribute set to `og_image`, etc, as in the example of touchpoints.digital.gov shown above. This change is live and the scanner will run this evening.

**Comment by gbinal** [comment]
Great, thank you!  I've confirmed this [in the API](https://api.gsa.gov/technology/site-scanning/v1/websites/touchpoints.digital.gov?API_KEY=DEMO_KEY), so we should be good now.  

Thanks for finding this, @ryanwoldatwork !!

**Comment by ryanwoldatwork** [comment]
thanks team!
