### ISSUE TITLE
change pulse source location 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1035]
and update documentation 

to here - https://github.com/GSA/federal-website-index/blob/main/data/dataset/pulse.csv

**Comment by akuny** [comment]
Data source in the builder script has been updated and the list has been rebuilt: https://github.com/GSA/federal-website-index/blob/6519971466afb8ac182b8fee01dcd6763448a833/builder/main.py#L9

**Comment by gbinal** [comment]
thanks!
