### ISSUE TITLE
prototype meta redirects scan 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1037]
Following up on #1028, we should now try to build this and see what we can find with it.

**Comment by gbinal** [comment]
Tentatively, I think we could call it `target_url_meta_redirect` and place it after `target_url_redirects` and before `final_url`.

**Comment by akuny** [comment]
This has been built and deployed: https://github.com/GSA/site-scanning-engine/pull/333

I'll extract the results and share them on Monday.

**Comment by gbinal** [comment]
There's a few issues that may be interfering with the best results.  Game to look at these notes and see if you see anything that could be fixed?  

https://github.com/GSA/site-scanning/issues/1043#issuecomment-2174004703
