### ISSUE TITLE
generate bulk trackerdb file 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1051]
From https://github.com/ghostery/trackerdb/

Specifically, the patterns files - https://github.com/ghostery/trackerdb/blob/main/db/patterns/.  

The goal is to get all of the data in those individual files into a spreadsheet.  Necessary columns are: 

name
category
website_url
domains
ghostery_id

Anything else is gravy.  Note that there may be multiple domains for an entry

**Comment by akuny** [comment]
Shared via Google Drive: https://docs.google.com/spreadsheets/d/1WeILsXjDWf-yaxtrCoZEnNiJQKD3DMvZuczrKm0cXuI/edit?usp=sharing

**Comment by gbinal** [comment]
THANKS!
