### ISSUE TITLE
public field data is off 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1054]
They are almost all FALSE when they should instead reflect what is [here](https://github.com/GSA/federal-website-index/blob/main/data/dataset/omb_idea.csv).

**Comment by akuny** [comment]
This has been fixed. The target URL list was accurate, but the problem was that the ingest service the engine uses to intake that list had the column order of the list slightly off.

**Comment by gbinal** [comment]
Rock - thank you.
