### ISSUE TITLE
some sites missing final URL TLD

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1061]
Looks like it's because the sites that have a `:` in their final url 

- poena.inl.gov
- kits.fnal.gov
- myhr.pnl.gov
- fnkits.fnal.gov
- hypermail.fnal.gov
- cdcvs.fnal.gov
- helpdesk.fnal.gov

**Comment by akuny** [comment]
Added a fix for this and redeployed: https://github.com/GSA/site-scanning-engine/pull/339

**Comment by gbinal** [comment]
great work on this!  closing
