### ISSUE TITLE
There's a larger number of sites with old scan dates 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1062]
About 1300 or so, by my count.  

[Folder of exports, for convenience](https://drive.google.com/drive/u/1/folders/1zGnXouD4CDDKsRet-67r8xseC6o3sJp8)

**Comment by akuny** [comment]
In an effort to better understand why certain websites have stale scan results (that is, scan results that were last updated prior to the vast majority of other scan results), we created a [GitHub Action](https://github.com/GSA/site-scanning-engine/actions/workflows/requeue-stale-scans.yml) called "Requeue stale scans" that selects all scan results that were last updated prior to three days before the current date and rescan them. Note that the three-day gap is arbitrary and can be adjusted as needed moving forward: https://github.com/GSA/site-scanning-engine/blob/8a1fa39b36ee3a4ec6692d0f0c32e7bc0795c108/libs/database/src/websites/websites.service.ts#L65

Using this action to scan these particular websites in isolation and then reviewing logs to better understand the problem led to a [fix](https://github.com/GSA/site-scanning-engine/pull/343) to the way the engine parses scan errors. After implementing this fix, all but one of the websites that were rescanned successfully wrote core results to the database.

**Comment by gbinal** [comment]
great work!!

**Comment by gbinal** [comment]
This was overwhelmingly successful.  There's 3-4 sites left that may be weirdos, so let's look one last time at those.
