### ISSUE TITLE
consider adding scan date/time to a11y details file

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1063]
There's an accessibility scan details file that is generated by [this action](https://github.com/GSA/site-scanning-engine/blob/main/.github/workflows/create-a11y-snapshot.yml).  

The need is to somewhere in it, wherever makes the most sense, add in a field similar to scan_date in the main scan.  I'd suggest calling the field scan_date.  

We assume that this would be for each individual scan entry.

**Comment by gbinal** [comment]
this is mostly done and should be deployed soon.

**Comment by luke-at-flexion** [comment]
This has been merged and deployed.

**Comment by gbinal** [comment]
woot!  Just checked it out and looks great.
