### ISSUE TITLE
Investigate "Evaluation failed" failed errors 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1064]
It looks like 6-7 websites fail their primary scans despite being live and the scan status is "Evaluation failed".  I suspect that this is a puppeteer error and not a network or server one.  

Can you investigate and 1) confirm what's happening when that error occurs and 2) see if you have any ideas on reducing/eliminating it.

**Comment by akuny** [comment]
Looking into these specific errors resulted in finding some cases where sub-scans of the primary scan were being tripped up by unhandled exceptions.

Merged [this PR](https://github.com/GSA/site-scanning-engine/pull/340) into main, redeployed, and reran the scans on 7/8-9.

Results are [here](https://github.com/GSA/site-scanning-engine/pull/340): there are no more primary scans with a status of `evaluation_failed`.
