### ISSUE TITLE
Implement new proposed actions schedule 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1070]
Here's the new proposed schedule - 

https://github.com/GSA/site-scanning-documentation/blob/new-schedule/pages/schedule.md

**Comment by luke-at-flexion** [comment]
I have reviewed the new schedule and no problems come to mind. I suspect that I wouldn't know, though, so Andy's input is likely to be more valuable.

**Comment by gbinal** [comment]
There's a PR for these that will get merged after review.

**Comment by luke-at-flexion** [comment]
All PRs merged; this should be 100%

**Comment by gbinal** [comment]
There's a little bit here left to do:  

Under: Analyze snapshots and target URL list

I think only one of those is now daily, when we'd wish for them all to be.  This might be because there's no longer (?) a 'generate all analysis' action (???)

Under: Archive Snapshots

The archive action ...

Perhaps we should break these and the others out [on this page](https://github.com/GSA/site-scanning-documentation/blob/new-schedule/pages/schedule.md) more individually

**Comment by luke-at-flexion** [comment]
I updated the workflow for **Analyze snapshots and target URL list** and also updated the **schedule.md** within the documentation repo to reflect the workflow name change. The workflow schedule has been merged, but the **schedule.md** changes still remain open under [PR-15](https://github.com/GSA/site-scanning-documentation/pull/15).

**Comment by gbinal** [comment]
great work - thanks!  

I'll give this a few days for the actions to begin flowing on their own and then close this once I verify it.
