### ISSUE TITLE
Onboard new teammate!!

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1072]

**Comment by akuny** [comment]
### Engineering Onboarding Checklist

- [ ] Link GSA email with GitHub account
- [ ] Add to "FAS - TTS - Solutions - Site Scanning" team
- [ ] Walk through these GH repos:
  - [ ] site-scanning
  - [ ] site-scanning-engine
  - [ ] federal-website-index
  - [ ] site-scanning-analysis
  - [ ] site-scanning-snapshots
  - [ ] site-scanning-documentation
- Successfully build and run the scan engine in local development environment:
  - [ ] Set up postgres
  - [ ] Set up redis
  - [ ] Configure local scan engine env
  - [ ] Run ingest CLI command locally
  - [ ] Run scan-site CLI command locally
- [ ] Successfully use CLI to work with deployed apps:
  - [ ] Install [Cloud Foundry CLI](https://docs.cloudfoundry.org/cf-cli/install-go-cli.html#pkg-mac)
  - [ ] Install [cg-manage-rds](https://github.com/cloud-gov/cg-manage-rds)
  - [ ] [Log in](https://cloud.gov/docs/getting-started/setup/) to CF CLI
  - [ ] Use CF CLI to grab a backup of postgres db

**Comment by gbinal** [comment]
Great work you two.  Closing.
