### ISSUE TITLE
Recognize Andy Kuny and thank him for all of his great work over the past few years!

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1098]
You're the best, @andy.  Site Scanning, GSA, and the US Federal Government thank you for your service.  We've loved working with you!!   Take care and don't be a stranger.  

And now, in recognition of your good work... a 21 comment salute.  

For ....

**Comment by gbinal** [comment]
[salute](https://media1.tenor.com/m/PLRzc5m6tBgAAAAC/salute-honour.gif)

[That time you added source fields to the data](https://github.com/GSA/site-scanning-engine/pull/182)...

**Comment by gbinal** [comment]
![salute](https://media1.tenor.com/m/ug8vdKLEYOoAAAAC/band-of-brothers.gif)

[That time you made a login detection scan](https://github.com/GSA/site-scanning-engine/pull/188)...

**Comment by gbinal** [comment]
![salute](https://media1.tenor.com/m/Fk57yabSTC0AAAAC/captain-america-salute.gif)

[That time you added analysis tools for us](https://github.com/GSA/site-scanning-engine/pull/198)...

**Comment by gbinal** [comment]
![salute](https://media1.tenor.com/m/Zs0LA6-ilX0AAAAC/han-solo.gif)

[That time you built an hsts detector](https://github.com/GSA/site-scanning-engine/pull/214)...

**Comment by gbinal** [comment]
![salute](https://media1.tenor.com/m/FH4il6nrwT8AAAAC/salute-navy.gif)

[That time you added end-to-end tests](https://github.com/GSA/site-scanning-engine/pull/215)...

**Comment by gbinal** [comment]
![salute](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExemhndXcwd2xkNHp3cDFrOG9vcnlicGI0a2lhc2UxaHhzMWlwY2VjdCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3ornkbVegziBt0PA1G/giphy.gif)

[That time you improved the DAP detection scan](https://github.com/GSA/site-scanning-engine/pull/220)...

**Comment by gbinal** [comment]
![salute](https://media1.tenor.com/m/UomfAYW5t_AAAAAC/top-gun-maverick-take-off.gif)

[That time you built a cloud services scan](https://github.com/GSA/site-scanning-engine/pull/221)...

**Comment by gbinal** [comment]
![salute](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNnNmZzJ4djlqYmJ5c2poaG41bXJ3Nmk1aGdvcTZ5andtMmQyb2pvbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l4pMattUYTTM7qpIk/giphy.gif)

[That time you refactored the DNS scan](https://github.com/GSA/site-scanning-engine/pull/226)...

**Comment by gbinal** [comment]
![salute](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbzU0cGN2NndwbW9saG4yY3ZpNGhvanVjb2s3amd5a2p4cXg4eTRhaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/8FG705NCsZM0kVJdyz/giphy.gif)

[That time you built a DNS scan](https://github.com/GSA/site-scanning-engine/pull/231)...

**Comment by gbinal** [comment]
![salute](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaTN4Z29hZWxqNnZ4bm9ubnB0bGZrOTJ1bGJycnN3d2dxYW51cTlleCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/fSAyceY3BCgtiQGnJs/giphy.gif)

[That time you added fields to the API](https://github.com/GSA/site-scanning-engine/pull/239)...

**Comment by gbinal** [comment]
![salute](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbWdnanplZWY5YzFsaDhpbXhvbm8wM2g1a2RobndpaGZmamdjNGM2MSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l3V0q1JDkTaUzpgm4/giphy.gif)

[That time you built a required links scan](https://github.com/GSA/site-scanning-engine/pull/241)...

**Comment by gbinal** [comment]
![salute](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExemliZGE2Nmloa3RjZGFkb2E3NzYxaDhwOTQxbW9oNXgzZTVjdm5odiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/D8xNev92dfqdG9FPx4/giphy.gif)

[That time you increased test coverage](https://github.com/GSA/site-scanning-engine/pull/243)...

**Comment by gbinal** [comment]
![salute](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdnZ2dGprNjhtemZzcGpxOTAwdmN3NWRxYm1hMGRhOHI3aTBnZmVycCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/h0G3ny3yfdQlx5h4aF/giphy.gif)

[That time you built a login provider scan](https://github.com/GSA/site-scanning-engine/pull/250)...

**Comment by gbinal** [comment]
![salute](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbnh5dWEybm1uZTJpeW94Ymg3bHZ5cDdzaWJham80bW16d3UyZzV1biZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/h4rwx4t4zoex49jhFE/giphy.gif)

[That time you prototyped a site search scan](https://github.com/GSA/site-scanning-engine/pull/261)...

**Comment by gbinal** [comment]
![salute](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdzdrOW1jdGZnbW95eG00dDVpdTAzNnRybTB3dWZ3NzhqbjdiZXZqMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/UIRDmXKym24lYzIQ8s/giphy.gif)

[That time you built a search.gov scan](https://github.com/GSA/site-scanning-engine/pull/263)...

**Comment by gbinal** [comment]
![salute](https://media1.tenor.com/m/r5-zVoaWQ08AAAAC/matthew-casey-salute.gif)

[That time you added a TLD filter column](https://github.com/GSA/site-scanning-engine/pull/270)...

**Comment by gbinal** [comment]
![salute](https://media1.tenor.com/m/g1rt6OsF-ZgAAAAC/adam-scott-salute.gif)

[That time you built an accessibility scan](https://github.com/GSA/site-scanning-engine/pull/281)...

**Comment by gbinal** [comment]
![salute](https://media1.tenor.com/m/7rAEf-NrpJEAAAAC/salute-hand-salute.gif)

[That time you built an SEO scanner for a million different meta tags](https://github.com/GSA/site-scanning-engine/pull/310)....

**Comment by gbinal** [comment]
![salute](https://media1.tenor.com/m/UWfx3flEOGIAAAAC/yes-sir.gif)

[That time you gave us more error messages](https://github.com/GSA/site-scanning-engine/pull/328)...

**Comment by gbinal** [comment]
![salute](https://media1.tenor.com/m/hNIn4kdL2MoAAAAC/chandler-moving-day.gif)

And last but not least, those years you've been both a solid dev and an affable friend to the project and all of us...  

We salute you.

**Comment by gbinal** [comment]
Ever forward, @akuny.

**Comment by akuny** [comment]
I am gobsmacked! It's been a fantastic journey, thank you for letting me take part in it.

![Thank you!](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbjBnOXNjbTlxemhuNWwxbm5yZWVkdDgwMXU4NzI1OThzdXZqcjIxeCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/PGSnPf27XvtTXGTKIG/giphy-downsized-large.gif)
