### ISSUE TITLE
Add encryption to the remaining paths that don't have it 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#110]
For our ATO, we're being asked to make every transit, including within the app, encrypted.  Cloud.gov has apparently done some work to make this possible.  We need to investigate and possibly implement.  ([Network diagram](https://docs.google.com/drawings/u/1/d/1MHgsONSKssgr21DfeLeO27uz41_118S8w-t8zbS_8Ms/edit))

Specifically, this will involve converting the following from HTTP to HTTPS:  
* Producer to postgres
* Producer to redis
* Postgres to api 
* Redis to consumer 
* Consumer to postgres

**Comment by wesley-dean-gsa** [comment]
@gbinal May I have some clarity on this request?

Initial research shows that Postgres and Redis both have default configuration settings to require encryption.

Redis: https://github.com/cloud-gov/aws-broker/blob/master/services/redis/redis.go#L111-L112
Postgres (RDS): https://github.com/cloud-gov/aws-broker/blob/master/common/dbconfig.go#L25

The service configuration does not disable SSL / TLS / encryption: https://github.com/GSA/site-scanning-engine/blob/main/cloudgov-deploy.sh

May I have some more detail on what needs to be updated?

Thanks!!

**Comment by gbinal** [comment]
Thanks for the updates and, yeah, I am certain that some (maybe much!) of this is stemming from me misunderstanding things.  Here's the short of it:  

* New rules say that basically everything has to be encrypted, whether in transit or at rest.  
* If you look at the network diagram linked at the start of this issue (which I made), you'll note that my understanding is that 5 connections are unencrypted instead of encrypted.  Generally speaking, the goal of this issue is to do the work so that those will be encrypted.  
* That said, as you mentioned in slack, container to container needs to be encrypted but if traffic doesn't leave the host, then I think that it doesn't have to be (see thread I'm about to share in slack).

**Comment by wesley-dean-gsa** [comment]
Right.  The services brokered by cloud.gov are encrypted both at-rest and in-transit per their default configurations.  There is no evidence that encryption is disabled.  Therefore, I'm comfortable in saying that the aforementioned connections are, in fact, encrypted.

**Comment by wesley-dean-gsa** [comment]
I see Ben's comment: https://gsa-tts.slack.com/archives/C0A1Z7L2U/p1637353150049500?thread_ts=1636572901.011300&cid=C0A1Z7L2U

> if you're using a brokered DB, all you should need to do is configure your client to use TLS

I'll explore that further, specifically with regards to the code I cited earlier.

**Comment by wesley-dean-gsa** [comment]
I'm reading through AWS's [documentation on connecting to ElastiCache](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption.html#connect-tls) for Redis nodes using in-transit encryption:

```
redis-cli -h Primary or Configuration Endpoint --tls -p 6379
```
("Primary or Configuration Endpoint" is a parameter that, in the documentation, is red and italicized)

Point: TLS traffic happens on port 6379, the standard port registered to Redis.

This is "interesting" because [Redis's documentation](https://docs.redis.com/latest/rc/security/database-security/tls-ssl/) asserts that port 16257.

**Comment by wesley-dean-gsa** [comment]
Tangentially, anecdotally, there's not a lot of documentation on using Redis with TLS; most content that I've read on the topic assert that Redis is typically used on a protected / isolated subnet where there is less of a need for encryption.

This is consistent with the overhead of using TLS with an in-memory cache reducing the effectiveness of said cache.  In the case of the site-scanner, Redis is used less as a caching mechanism and more of a queuing system.

**Comment by wesley-dean-gsa** [comment]
https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#DATABASE-URL
^ how the URL to the database is provided to the application running on cloud.gov

**Comment by wesley-dean-gsa** [comment]
```
return {
    type:        'postgres',
    url:         configService.get<string>('database.url'),
    entities:    [Website, CoreResult, SolutionsResult],
    synchronize: true,
    ssl:         true,
};
```

^ update [our code](https://github.com/GSA/site-scanning-engine/blob/main/libs/database/src/database.module.ts#L19-L24) to include the `ssl: true,` option to address the Postgres concerns.

**Comment by wesley-dean-gsa** [comment]
```
   redis: {
      host: configService.get('redis.host'),
      port: +configService.get<number>('redis.port'),
      password: configService.get('redis.password'),
      tls: configService.get('redis.env') === 'dev' ? undefined : {}
    },
```

^ [our code for Redis](https://github.com/GSA/site-scanning-engine/blob/main/libs/message-queue/src/message-queue.module.ts#L18-L23) already uses TLS in non-dev environments

**Comment by wesley-dean-gsa** [comment]
Created a [PR](https://github.com/GSA/site-scanning-engine/pull/128) for the update to the database module configuration to require SSL.

**Comment by wesley-dean-gsa** [comment]
Created another [PR](https://github.com/GSA/site-scanning-engine/pull/129) to allow self-signed certificates.  This new PR has been merged and deployed to prod.  All tests show that the deployment was successful.

```
  useFactory: (configService: ConfigService) => {
    return {
      type: 'postgres',
      url: configService.get<string>('database.url'),
      entities: [Website, CoreResult, SolutionsResult],
      synchronize: true,
      ssl: {
        rejectUnauthorized: false,
      }
    };
```

https://github.com/GSA/site-scanning-engine/blob/main/libs/database/src/database.module.ts#L18-L27
^ updated code; note the `rejectUnauthorized: false` line

**Comment by wesley-dean-gsa** [comment]
Updated code has been successfully deployed and appears to be functioning properly.
