### ISSUE TITLE
Get background for ATO sessions

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#111]
Gray is handling the ATO process, but needs an engineer to explain the following prompt to him a bit more so that he can speak to it.  Once an engineer is familiar with the system, this should only take 3-4 minutes.  

_"Get clarification about how password (and token) connects with redis, s3, and postgressql from the 3 applications..."_

Gray then needs to ping Douglas with the results 

... 

Note: There are more questions in the comments in the doc.  

** underlying cloud.gov urls to them to scan; ensure set up to block access **

--- 

question about recent patch request

**Comment by wesley-dean-gsa** [comment]
The cloudgov-deploy.sh script creates user-provided API keys:
https://github.com/GSA/site-scanning-engine/blob/main/cloudgov-deploy.sh#L73-L99

These keys are then imported into running applications via the `user-provided-api-key` service:
https://github.com/GSA/site-scanning-engine/blob/main/manifest.yml#L8

Applications (e.g., the API) are able to access the credentials using Cloud Foundry's [VCAP_SERVICES](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP-SERVICES)
https://github.com/GSA/site-scanning-engine/blob/main/apps/api/src/website/config/api.config.ts#L7-L8

**Comment by wesley-dean-gsa** [comment]
it's possible to rotate user-provided service instances (e.g., credentials):
https://docs.cloudfoundry.org/devguide/services/user-provided.html#update

However, I don't know that there is a mechanism by which credentials and such are rotated automatically (e.g., AC-2(1)) on a periodic basis.

Per the [Rotating Service Credentials](https://cloud.gov/docs/ops/service-credential-rotation/) documentation, credentials may be rotated "by deleting and recreating services instances, but when this is not an option, [the cloud.gov support team] will rotate credentials manually by request."

**Comment by wesley-dean-gsa** [comment]
Note: the [cloudgov-deploy.sh](https://github.com/GSA/site-scanning-engine/blob/main/cloudgov-deploy.sh) script will not recreate services (e.g., credentials) if they already exist; if a given service already exists, a message is displayed / logged:

https://github.com/GSA/site-scanning-engine/blob/main/cloudgov-deploy.sh#L40

Therefore, running `cloudgov-deploy.sh` will not automatically rotate credentials.

**Comment by gbinal** [comment]
done!!
