### ISSUE TITLE
Add a scan for IPv6 compliance

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#113]
For each page, detect IPv6 compliance.  

The ideal method for doing this would be to try and connect to each page via IPv6 and see if it works, but I assume that an easier method would just be to look for an `AAAA` record.  Let's discuss the level of effort and sustainability of either approach or if there's other ideas.  

The data field would just be IPv6: True/False (field: ipv6).

**Comment by danielnaab** [comment]
This was previously completed, closing...
