### ISSUE TITLE
Generate a chunk of terminal logs

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1168]
Goal:  Generate and save a text file (or whatever) of what the terminal output looks like when site scanning engine runs locally against 5-10 websites (any will do).  It should include whatever scans we are currently running in production.

**Comment by luke-at-flexion** [comment]
I have captured the scanning logs for 8 urls. The file can be found here: https://drive.google.com/file/d/1gcmaHTHdooIF-WDwJ8ctv01b7Fil7Vjs/view?usp=drive_link

These are the urls that were scanned:
- eauth.fhwa.dot.gov
- fedcenter.gov
- apps.usfa.fema.gov
- noaa.gov
- trade.gov
- tn.usembassy.gov
- www.itrd.gov
- www.irs.gov

**Comment by luke-at-flexion** [comment]
I have captured the scanning logs for 8 urls. The file can be found here: https://drive.google.com/file/d/1gcmaHTHdooIF-WDwJ8ctv01b7Fil7Vjs/view?usp=drive_link

These are the urls that were scanned:
- eauth.fhwa.dot.gov
- fedcenter.gov
- apps.usfa.fema.gov
- noaa.gov
- trade.gov
- tn.usembassy.gov
- www.itrd.gov
- www.irs.gov

**Comment by gbinal** [comment]
Rock.  Thank you!!!

**Comment by gbinal** [comment]
(note to self, I've hosted a copy [here](https://docs.google.com/document/d/1qV-EfQ0u_Gw13qeQrUfBKwQOP2xDP7GsnGBmk_izd7U/edit))
