### ISSUE TITLE
run site scanning against all of certain error types locally

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1199]
Run the site scanning engine on a local machine against [these 2900 sites](https://docs.google.com/spreadsheets/d/13abir8932pCKXveWE5c6CfaD8amFxKG-Sd-yPvunG9E/edit?gid=1332760371#gid=1332760371) and see what we see.  

I'm trying to test for these error messages: evaluation failed, execution context destroyed, page frame not ready, timeout, and unknown error.

**Comment by luke-at-flexion** [comment]
I have uploaded a CSV of the local scan results. It is located here: https://drive.google.com/file/d/102Q_TYTfGOz7G6heuGv_HkrU4Sw3ttoV/view?usp=drive_link

**Comment by gbinal** [comment]
thanks!  great work.
