### ISSUE TITLE
Track possible edits to the query builder

### ISSUE THREAD

**Issue by laurenancona** [GSA/site-scanning#12]
from https://github.com/18F/site-scanning/issues/914

* Live URL - https://site-scanning.api.data.gov/

Ideas: 
* [ ] check to see if URL window gets weird after a page reload, after a query has been selected
* [ ] update workflow for spreadsheet users - #15
* [ ] re-ad excel link
* [ ] figure out how to add back target URL filter (note that it's added to the endpoint, not as a query parameter)
* [ ] rethink/gutcheck the filter display names
* [ ] rethink 'What Are These Filters'?  
* [ ] validate google sheet code
* [ ] rethink what a first time user sees, and how to explain to them what to do on the page.  
* [ ] Consider having a field to add your own api key
* [ ] update link to google sheets for external users
* [ ] gutcheck and possibly improve field names and filters on left side
* [ ] ~consider adding a parenthetical example (e.g. fbi.gov) to the filters that have text fields~ [Note - maybe we hold on this.  It'll take a touch more work to do right than I thought ([link](https://github.com/18F/site-scanning-query-builder/blob/50b193cc3251d58653954060473ea3b85cd80db5/src/components/available-field.js#L27))).

**Comment by gbinal** [comment]
This is on hold while we prioritize the rest of the project.

**Comment by gbinal** [comment]
Closing this issue for now until we decide to restart the query builder effort.
