### ISSUE TITLE
MVP dashboard for scan data benchmarking

### ISSUE THREAD

**Issue by laurenancona** [GSA/site-scanning#121]
As a site scanning program manager, I have a way to view scan data over time, aggregated to meaningful metrics that allow analysis for data quality and completeness.

Based on [this template](https://docs.google.com/spreadsheets/d/1qHzTpJNahLFRCgX6MqPcI6yxC3YsGGD96-eEmDaz-JA/edit#gid=2130082636), each new weekly scan data should be rolled into the analysis as it's available (this can be done manually at first, but would be nice to automate via Google Scripts eventually).

**Comment by gbinal** [comment]
Bumping this into the next sprint, but also - depending on if you get to a good place with this in the next day or so - I'd love to take a crack, too.

**Comment by gbinal** [comment]
Alright - [here's an MVP](https://docs.google.com/spreadsheets/d/1Pm0mUz7BXCPv5mLqkU4FNuAA2buhfdNV5cOl4IqWtew/edit#gid=0) for this!

**Comment by gbinal** [comment]
done!
