### ISSUE TITLE
[draft] Create a prototype standards report 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1240]
In [this folder](https://github.com/GSA/site-scanning-analysis/tree/main/reports), similar to what we have with the IDEA reports. 

The report should run daily, as part of the [generate all reports action](https://github.com/GSA/site-scanning-analysis/actions), but also exist as a standalone action like all of the others do.  

Let's call it the standards report and make the filenames standards-agency.csv and standards-bureau.csv.  

The data should be based off of the `unique_final_websites_location` hosted file.  

For standards-agency.csv

Agency  | Number of Websites | Number of Websites With Page Title | Number of Websites With Page Description | Number of Websites with Government Banner |  Percent of Websites With Page Title | Percent of Websites With Page Description | Percent of Websites with Government Banner
-- | --- | -- | -- | -- | -- | -- | --
Acme | 12  | 10| 2| 12| 100% | 100% | 100%

For standards-bureau.csv

Agency | Bureau | Number of Websites | Number of Websites With Page Title | Number of Websites With Page Description | Number of Websites with Government Banner |  Percent of Websites With Page Title | Percent of Websites With Page Description | Percent of Websites with Government Banner
-- | -- | -- | -- | -- | -- | -- | -- | --
Acme | OIG | 2  | 2| 2| 2| 100% | 100% | 100%
Acme | TTS | 10 | 8| 0|10  | 80% | 0% | 100%

**Comment by luke-at-flexion** [comment]
Currently the idea report is not part of the generate-all-reports workflow run. It is run in a separate workflow and only scheduled once a week ( 00:00 UTC Tuesdays). The generate-all-reports runs every day at 13:00 UTC. Would you like this added in with the generate-all-reports or would you like it to be separated out like the idea report and run on it's own schedule?

**Comment by gbinal** [comment]
Ah, good to know.  Eh, don't worry about the idea reports.

**Comment by gbinal** [comment]
great work, @luke-at-flexion
