### ISSUE TITLE
update standards report

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#1271]
https://github.com/GSA/site-scanning-analysis/blob/main/reports/standards.csv

In column D, the count of websites with the banner, should be whole numbers like columns B and C are.  Then also, the total count at the bottom of column D should be made to work.

**Comment by luke-at-flexion** [comment]
This should be complete, see: https://github.com/GSA/site-scanning-analysis/blob/main/reports/standards.csv

**Comment by gbinal** [comment]
rock - thanks!
