### ISSUE TITLE
Update HttpService / HttpModule to use nestjs/axios

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/site-scanning#133]
While watching a deployment to production today (Wednesday, December 22nd), I saw this message fly past:
```
WARN [HttpService] DEPRECATED! "HttpModule" (from the "@nestjs/common" package) is deprecated and will be removed in the next major release. Please, use the "@nestjs/axios" package instead.
```

The "will be removed in the next major release" part was what caught my eye.  We should probably follow the supplied recommendation so that we can continue to use current releases, particularly when applying security patches.

**Comment by wesley-dean-gsa** [comment]
**HttpService**

```
libs/core-scanner/src/core-scanner.service.spec.ts
11:import { HttpModule, HttpService } from '@nestjs/common';
23:  let httpService: HttpService;
61:    httpService = module.get<HttpService>(HttpService);
82:    jest.spyOn(httpService, 'get').mockImplementationOnce(() => of(resp));

libs/core-scanner/src/core-scanner.service.ts
4:  HttpService,
27:    private httpService: HttpService,
176:    const resp = await this.httpService

libs/ingest/src/ingest.service.spec.ts
3:import { HttpService } from '@nestjs/common';
10:  let mockHttpService: MockProxy<HttpService>;
15:    mockHttpService = mock<HttpService>();
30:          provide: HttpService,
31:          useValue: mockHttpService,

libs/ingest/src/ingest.service.ts
2:import { HttpService, Injectable } from '@nestjs/common';
12:    private httpService: HttpService,
23:    const urls = await this.httpService
```

**HttpModule**

```
libs/core-scanner/src/core-scanner.module.ts
3:import { HttpModule, Module } from '@nestjs/common';
7:  imports: [BrowserModule, LoggerModule, HttpModule],

libs/core-scanner/src/core-scanner.service.spec.ts
11:import { HttpModule, HttpService } from '@nestjs/common';
46:      imports: [HttpModule],

libs/ingest/src/ingest.module.ts
4:import { HttpModule, Module } from '@nestjs/common';
8:  imports: [HttpModule, WebsiteModule, DatabaseModule, LoggerModule],
```

**Comment by wesley-dean-gsa** [comment]
https://github.com/nestjs/nest/commit/6ede3aef2c21cb6bb2a9424a5b9969c8281fc762

^ this deprecation happened on February 8th, 2021.  I'm struggling to find any additional documentation on the migration path.  However, comments in the code suggest that we need to change `import` statements for `HttpModule` and `HttpService` from `@nestjs/common` to `@nestjs/axios` .  I'll solicit advice from folks more current on this topic and post it here.

**Comment by wesley-dean-gsa** [comment]
https://github.com/nestjs/nest/pull/6349

^ the PR associated with the change relates to "v8 major release"

> common: deprecate HttpModule to remove hard dependency on the axios library. HttpModule is published as a new @nestjs/axios package now

However, there is a notation that this PR does introduce a breaking change.  It's not documented which change breaks stuff or what is broken.  Also, per my previous comment, there is a dearth of migration documentation.  It still appears that we need to update our `import` statements and I'm hoping the change is limited to that, but I don't have solid evidence to support that assertion.

**Comment by danielnaab** [comment]
#247 This should be swapped out at some point, and treated as a tech debt item.

**Comment by akuny** [comment]
Resolved by https://github.com/GSA/site-scanning-engine/pull/189
