### ISSUE TITLE
Find / create / update documentation on deploying to non-prod environments

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA/site-scanning#134]
If there's documentation on how to deploy to environments other than prod (e.g., dev), I haven't found it yet.

If it exists, we should update it and make it more findable.

If it does not exist, we should create it.

Why?  I would like to be able to run tests beyond the CI/CD's build test to verify if a release works properly before pushing it to prod (e.g., `cf push`).

**Comment by wesley-dean-gsa** [comment]
Tangentially, it appears that there's a deploy action scheduled to run at roughly 5:25pm Eastern daily.  So, supposing that we try to build something and push it to dev where it promptly fails to work as-expected.  Then what?  In other words, if we know that something doesn't work and that the system is about to deploy it to prod anyways, what do we do?

**Comment by gbinal** [comment]
we're close on this but not quite there yet.  Should be able to finish this week though.

**Comment by wesley-dean-gsa** [comment]
[PR 139](https://github.com/GSA/site-scanning-engine/pull/139) has been merged and the work on this has been completed, so I'm closing out this ticket.
