### ISSUE TITLE
Deprecate unused target URL locations 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#139]
To follow up/wrap up #72.

**Comment by gbinal** [comment]
We've identified the various duplicate file locations in #72.  After #72 has been shipped, let's go back and delete the unused two locations ([here](https://github.com/GSA/data/blob/master/dotgov-websites/site-scanning/current-federal-subdomains.csv) and [here](https://github.com/cisagov/dotgov-data/blob/main/dotgov-websites/site-scanning/current-federal-subdomains.csv))

**Comment by gbinal** [comment]
We've [added language](https://github.com/GSA/data/tree/master/dotgov-websites/site-scanning) to github.com/gsa/data that takes care of what we need there.  And [this PR](https://github.com/cisagov/dotgov-data/pull/53) seeks to clean up the CISAGOV repo.

**Comment by h-m-f-t** [comment]
Do y'all use the files at https://github.com/GSA/data/tree/master/dotgov-websites? In particular, I'd like to clear the data from ocsp-crl.csv, though I'd be happy to have the README point to cisagov/dotgov-data generally.

**Comment by gbinal** [comment]
@h-m-f-t - we're okay with you doing whatever you want with that folder.  Thanks for checking!
