### ISSUE TITLE
Kibana dashboard

### ISSUE THREAD

**Issue by laurenancona** [GSA/site-scanning#141]
### Config:
- [x] Filter: by app deployment tier
- [ ] Query: when the ingest jobs run: `github-action-ingest-XXXXXX`
- [ ] Query: when snapshots ran: `github-action-create-snapshot-XXXXXX`
- [ ] When Redis queue is cleared: `github-action-clear-queue-XXXXXX`

### Charts to build:
- [ ] ingest jobs
- [ ] snapshot jobs 
- [ ] timeline of jobs
- [ ] monitor queue status - messages like: `{"message":"queue status","queue":{"count":75248,"activeCount":3}}`

### Possible additions:
- [x] Is there a scan id with each log message?
- [x] log as JSON: RabbitMQ > cloud.gov as some sort of ID
- [ ] more jobs?: github-action-[jobname]-scanid

**Comment by gbinal** [comment]
In progress.  We're waiting for a followup from the cloud.gov team then should be able to wrap this one up, likely this sprint.

**Comment by gbinal** [comment]
More data is being gathered.  We've still got some changes we want to push though.

**Comment by gbinal** [comment]
done!
