### ISSUE TITLE
Optimize/debug puppeteer usage

### ISSUE THREAD

**Issue by danielnaab** [GSA/site-scanning#142]
Review the usage of Puppeteer and make changes to optimize:

* Scan speed
* Memory usage
* Resilience to memory leaks or other long-running process problems
* Consider Chromium sandbox usage. See: https://github.com/GSA/site-scanning-engine/blob/main/libs/browser/src/browser.service.ts#L26

**Comment by gbinal** [comment]
We've made some progress on this, but it's still in the works.  We were out some of last week, but should have more time this week.  Should be able to complete it this week.

**Comment by gbinal** [comment]
This is pretty much done.  It doesn't fix the core issue we're hoping to fix, but was still productive.
