### ISSUE TITLE
Fail fast on scan errors

### ISSUE THREAD

**Issue by danielnaab** [GSA/site-scanning#184]
Investigate the speed of scan failures, and look for opportunities to "fail fast."

Context: This chart shows a slowdown introduced with https://github.com/GSA/site-scanning/issues/172 . 18:20-20:00 is a faster complete scan, 22:30-01:50 a slower one. This PR waits for all page scans to return pass/fail, while previously scans would stop on the first failure. At least one of the scans (likely the not found scan, which uses the `@nestjs/common` `HttpService`) is failing faster than the rest (likely the Puppeteer scans).

<img width="838" alt="image" src="https://user-images.githubusercontent.com/136512/155531357-26e9f6da-ec27-43f6-a031-f2e420e0907f.png">

**Comment by danielnaab** [comment]
[AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) might be helpful here, to cancel the mega Promise.all() [here](https://github.com/GSA/site-scanning-engine/blob/main/libs/core-scanner/src/core-scanner.service.ts#L31).

**Comment by gbinal** [comment]
_[Note from Gray - we discussed and still want to keep this open]_

**Comment by gbinal** [comment]
(moving to [the backlog](https://github.com/GSA/site-scanning/issues/337) for now)
