### ISSUE TITLE
Some URLs have incorrect redirect status

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#203]
There's two batches of these:  
* URLs that have  `Target_URL_Redirects` = `false` and `Final_URL_same_domain` = `false`
* URLs that have  `Target_URL_Redirects` = `false` and `Final_URL_same_website` = `false`

There's only about 20 of the first, but there's about 700 of the second.  In these cases, it appears that the `Target_URL_Redirects` field should = `true`.  

* Investigate
* Plan and implement a remedy

**Comment by akuny** [comment]
If possible, can you provide some specific URLs?  These cases are probably similar to the examples below: there is no server-side redirect, but the browser is redirected by scripting logic on the client side. If there are other specific cases, I can investigate those as well.

![Screen Shot 2022-05-27 at 2 56 39 PM](https://user-images.githubusercontent.com/13356991/170773593-d6a0cbba-c3f2-4491-ac7f-95a2a3e8e4db.png)

**Comment by gbinal** [comment]
Closing in favor of #248
