### ISSUE TITLE
dap parameters fields are missing data

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#205]
In the CSV, there's no DAP_parameters data, whereas in the past, there were dozens of columns of it.

**Comment by gbinal** [comment]
This can be easily seen by looking at a CSV export, and in the `dap_parameters_final_url` field, every single row is empty (null).  This can be seen in [the 3-22-22 export](https://docs.google.com/spreadsheets/d/17R93lR4CelT6yP5O10dJiYRHQMeggUHJVO4Pai4j_vA/edit#gid=419379436) (column AI).  

One note though is that when this field is being appropriately populated, the end result actually has the CSV populating numerous columns, one for each detected parameter.  This can be seen starting in column BI, in an [export from Nov., 2021](https://docs.google.com/spreadsheets/d/1hO5Xf54cVDQSq7L_hX7bC16oQquYiTizYLKWpjCbsek/edit#gid=2145872124).

**Comment by lgarceau768** [comment]
Link to the PR https://github.com/GSA/site-scanning-engine/pull/172, made some of the requested changes just need to finish migrating some of the sorting functionality of the csv headers into another function. Also need to add more test coverage for the sorting function (probably about another days worth of work before completion and for it to be ready to merge.

**Comment by gbinal** [comment]
done
