### ISSUE TITLE
Filter by each scan status field in API

### ISSUE THREAD

**Issue by danielnaab** [GSA/site-scanning#211]
The API previously supported filtering on the core result scan status. Now that the API has multiple status fields, the API should be updated to support filtering on each of them. Also, the TypeORM filtering is string-based, meaning that we don't have type-safety when columns are renamed/removed; something to make the code resilient to future changes should be added.

AC:
* User may filter on each scan status
* Tests and/or type safety is implemented so if database columns are renamed, the build or CI will fail

**Comment by gbinal** [comment]
This isn't particularly urgent, or even a priority for what it's worth.

**Comment by danielnaab** [comment]
As of 6/22, this is still valid. #247

**Comment by gbinal** [comment]
Thinking on this further, I agree that it's valid and would have value, but I'm going to close the issue until this becomes a priority.  We won't forget about what the API can be queried by/can't be queried by, and if an appetite for this arises, it'll be easy to reopen or recreate this.
