### ISSUE TITLE
create data dictionary for Target URL list

### ISSUE THREAD

**Issue by laurenancona** [GSA/site-scanning#215]

**Comment by laurenancona** [comment]
Sheet for data dictionary: https://docs.google.com/spreadsheets/d/196b4_4eLnsvzNsBMs1i6thrbT0IOi0HDZTqu1sdIz6Y/edit#gid=0

**Comment by gbinal** [comment]
done - https://github.com/GSA/site-scanning-documentation/blob/main/data/Target_URL_List_Data_Dictionary.csv
