### ISSUE TITLE
MVP a login scan

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#233]
Using these [notes](https://docs.google.com/document/d/1r4eoDUd8J1r52INiiWks-y-6m5k9cYcIcC1Lw-VmNxY/edit#), we should take a first pass at this.

**Comment by akuny** [comment]
One question for clarification: where in the column order for the snapshot CSV file should this new `login-detected` column reside?

**Comment by gbinal** [comment]
done!  very excited to see this!
