### ISSUE TITLE
Update FY22/FY23 budget request

### ISSUE THREAD

**Issue by laurenancona** [GSA/site-scanning#25]
from https://github.com/18F/site-scanning/issues/917

We should reformat our budget request into [the spreadsheet style](https://docs.google.com/spreadsheets/d/1yfu6zIYkapjE7ShIYh5XIbYz5MwZVtHaPM8aDRujmEs/edit#gid=0) that Phil uses.

**Comment by gbinal** [comment]
this is [done](https://docs.google.com/spreadsheets/d/13qMvoQvQKVtD4dflMhvFREzMZ4xwIfKKpF2nKrotB4o/edit#gid=0)!
