### ISSUE TITLE
Track ideas for a Blocklist

### ISSUE THREAD

**Issue by laurenancona** [GSA/site-scanning#27]
from https://github.com/18F/site-scanning/issues/912

The initial cut of websites results in 170,000 results.  Many of those would be good to ignore though.  

Starting from [this list](https://github.com/18F/g-analytics/blob/18f-pages/projects/dap-subdomain-report/assets/ignore-list.md), below is another set of candidates for ignoring.  

* begins with a wildcard (*)
* begins with 5 or more numerals?
* begins with a numeral then www (e.g. 3www.x.gov)
* begins with `access.`, `access-`, or `access_`.  
* begins with acquia
* adfs - activedirectory
* admin
* assets, assets-, assets1, assets2, assets3

Working on it [here](https://docs.google.com/spreadsheets/d/1YcBrLoeHcdmUuiPwmyBCMHBfAHrDYd4RUFc_cQ1JLdc/edit#gid=230126362)

**Comment by gbinal** [comment]
[Here's](https://github.com/18F/g-analytics/blob/18f-pages/projects/dap-subdomain-report/assets/ignore-list.md) an earlier ignore list we came up with that we should factor in.

**Comment by laurenancona** [comment]
Created here: https://github.com/GSA/federal-website-index/blob/main/criteria/ignore-list.md
