### ISSUE TITLE
bug?  fedramp.gov and DAP

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#279]
Someone mentioned this week that we are showing `fedramp.gov` as not having DAP but they do.  I've confirmed those two aspects so we should investigate.  

https://api.gsa.gov/technology/site-scanning/v1/websites/fedramp.gov?api_key=DEMO_KEY

**Comment by akuny** [comment]
As currently configured, the site scanner system determines whether or not a given URL's website has DAP enabled by checking for the existence of the following identifier in one of the website's outbound requests:

`UA-33523145-1`

As of the 8/27/2022 scan, 6566 URLs point to websites that use this identifier, and `fedramp.gov` is not one of them. So, we may need to revisit the requirements for what exactly constitutes DAP participation.

**Comment by gbinal** [comment]
Gotcha - thanks for confirming.  

Moving this issue to this sprint and we can investigate it further together in an upcoming coworking session

**Comment by gbinal** [comment]
This was fixed a while back.   Closing!
