### ISSUE TITLE
Update the target URL list github action to point to new location 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#288]
Right now, the new file goes [here](https://github.com/GSA/federal-website-index/blob/main/data/site-scanning-target-url-list-automated.csv). 

After we make a few other updates to the process, we should change it to overwrite [here](https://github.com/GSA/federal-website-index/blob/main/data/site-scanning-target-url-list.csv).

**Comment by akuny** [comment]
This went live 9/29/2022.
