### ISSUE TITLE
automate the (up to) 4 analyses

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#298]
It's not for sure, but if we end up making 1 or more github actions for #291, I think we should set them on some sort of weekly routine to run.

**Comment by gbinal** [comment]
@akuny - my vote would be for the analysis reports to run a day or two after the scheduled list generation (which is on wednesdays, right?).  That way, the two  website-index report will be in sync (i.e. looking at the same data/timeframe) for most of each week.

**Comment by akuny** [comment]
I created a new action that re-runs the three analysis reports weekly on Thursday at 10:00 PM UTC (5 PM EST).
