### ISSUE TITLE
 Create an analysis report for the target URL list creation process

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#301]
Each time that the target URL list generation github action runs, have it capture the below numbers and overwrite them [here](https://github.com/GSA/federal-website-index/blob/main/data/analysis/generation-report.csv).  

* Number of urls ingested from [source 1]
* Number of urls ingested from [source 2]
* Number of urls ingested from [source 3]
* Number of urls ingested from [source 4]
* Total Number of urls ingested
* Total number of urls after non-federal removed
* Total number of urls after dedupping
* Total number of urls after the ignore list has been applied

The second half of ^^^ assumes that that is the order of the process involved, and that there aren't other stages that would make sense to include.

**Comment by akuny** [comment]
The script that builds the federal website index now produces a document containing stats about the data sources used during the process: https://github.com/GSA/federal-website-index/blob/main/data/site-scanning-target-url-list-analysis.csv
