### ISSUE TITLE
MVP a CMS detector

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#311]
Possibly using @BenBalter 's outstanding [Site Inspector code](https://github.com/benbalter/site-inspector) (discussed [here](https://ben.balter.com/2021/01/11/analysis-of-federal-dotgov-domains-pre-biden-edition/)), a new scan would MVP detecting CMS.  

Field name: `cms`

**Comment by benbalter** [comment]
https://github.com/wappalyzer/wappalyzer is the more "modern" code that site inspector uses under the hood.

**Comment by gbinal** [comment]
fieldname: `dns_hostname`

library of responses is [here](https://docs.google.com/spreadsheets/d/1YXD5NOXo1AVvK3z1kYrX5u0Dam2PgJo8Wp_gVCZXzB8/edit#gid=1234467005) (but note the 4 values I said to ignore.  Each of those are at the end of the string.

**Comment by gbinal** [comment]
This field should go after `Source List - Other` and before `Cloud.gov Pages`.

**Comment by gbinal** [comment]
the code that manages the snippets that are being searched for is [here](https://github.com/GSA/site-scanning-engine/blob/main/libs/core-scanner/src/scans/cms.ts).
