### ISSUE TITLE
MVP cloud detection scan 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#314]
Possibly using @BenBalter 's outstanding [Site Inspector code](https://github.com/benbalter/site-inspector) (discussed [here](https://ben.balter.com/2021/01/11/analysis-of-federal-dotgov-domains-pre-biden-edition/)), a new scan would MVP detecting cloud hosting.  

Field name: ~`host`~  `cloud_provider`

And I think that the values field should be e.g. `us-gov-west-1.compute.amazonaws.com` or `github.io` or `herokuapp.com`

**Comment by benbalter** [comment]
There's also `cloud_provider` field, which does [a lookup on the hostname](https://github.com/benbalter/site-inspector/blob/effc4693cfe6431ce0298bb6d04b8d31390b8963/lib/data/cloud.yml).

**Comment by gbinal** [comment]
For examples, look on [this page](https://ben.balter.com/2021-analysis-of-federal-dotgov-domains/domains/), under the PAAS column, for `Amazon Web Services`, `Azure`, etc.

**Comment by gbinal** [comment]
Initial test results [here](https://docs.google.com/spreadsheets/d/1vdbGPI0gPjJPt0Lv_QiCRNNkLCEIZ-6ukEdh92qj4Lk/edit#gid=393914998).

**Comment by gbinal** [comment]
Next steps: 
* Call with Ben to get his thoughts 
* Email with Ben, Eric, and Cameron to get their thoughts 
* Generate string library for Andy to employ

**Comment by gbinal** [comment]
fieldname: dns_hostname

library of responses is [here](https://docs.google.com/spreadsheets/d/1YXD5NOXo1AVvK3z1kYrX5u0Dam2PgJo8Wp_gVCZXzB8/edit#gid=1234467005) (but note the 4 values I said to ignore. Each of those are at the end of the string.

In the snapshots, this field should go after IPv6 Compliance and before Source List - Federal .Gov Domains

**Comment by gbinal** [comment]
done!
