### ISSUE TITLE
MVP a CDN detector 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#316]
@benbalter - because you're such a mensch and responded to #311 and #314, I'm at mentioning you again on this issue in case you have any further thoughts beyond my usual go to (which is to start by seeing how (site inspector)[https://github.com/benbalter/site-inspector] works).  :)

**Comment by benbalter** [comment]
https://github.com/benbalter/site-inspector can detect CDNs based on the host name (although the current list is limited, but easily exapandable - https://github.com/benbalter/site-inspector/blob/effc4693cfe6431ce0298bb6d04b8d31390b8963/lib/data/cdn.yml#L2)

**Comment by gbinal** [comment]
Also, it turns out that the good folks at CISA have made - https://github.com/cisagov/findcdn

**Comment by gbinal** [comment]
done!
