### ISSUE TITLE
Gray & Lauren take a mallet to the analysis

### ISSUE THREAD

**Issue by laurenancona** [GSA/site-scanning#317]
* [ ] [snapshot - primary](https://github.com/GSA/site-scanning-analysis/blob/main/reports/snapshot-primary.csv)
* [ ] [snapshot - all](https://github.com/GSA/site-scanning-analysis/blob/main/reports/snapshot-all.csv)
* [x] [target URL list analysis](https://github.com/GSA/site-scanning-analysis/blob/main/reports/target-URL-list.csv)
* [x] [index generation process analysis](https://github.com/GSA/federal-website-index/blob/main/data/site-scanning-target-url-list-analysis.csv)

**Comment by laurenancona** [comment]
#308

**Comment by gbinal** [comment]
did this enough I think.  closing for now.
