### ISSUE TITLE
Create two extra outputs of the ignored URLS

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#319]
When the website index is built, a certain number of urls are removed as a result the ignore list being applied, and then a further set of URLs are removed for being non federal.  

It would be helpful to have each of those sets of URLs (the list of URLs being removed from the website index) to be written to a file for debugging and visibility purposes.  

The files could live and be overwritten at: 
* https://github.com/GSA/federal-website-index/blob/main/data/site-scanning-target-url-list-removed-ignore.csv
* https://github.com/GSA/federal-website-index/blob/main/data/site-scanning-target-url-list-removed-nonfederal.csv

**Comment by akuny** [comment]
Those two files are now created/updated whenever the build script runs.
