### ISSUE TITLE
rename field in index creation analysis report

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#320]
For [this file](https://github.com/GSA/federal-website-index/blob/main/data/site-scanning-target-url-list-analysis.csv), I think we would want to rename `url list length after non-.gov urls removed` to `url list length after non-federal urls removed`

**Comment by akuny** [comment]
This one is done: see https://github.com/GSA/federal-website-index/blob/main/data/site-scanning-target-url-list-analysis.csv
