### ISSUE TITLE
make a table of all automated steps, and relevant documentation 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#322]
What's the step; when is it scheduled to run; where can it be manually run; where are the sub-steps that take place in it described; where is the code for it

**Comment by akuny** [comment]
| action                        | runs on               | specified in                                                                                | manually run at                                      |
| ----------------------------- | --------------------- | ------------------------------------------------------------------------------------------- | ---------------------------------------------------- |
| Build federal website index   | Wednesday, 10 PM UTC  | https://github.com/GSA/federal-website-index/blob/main/.github/workflows/build-list.yml     | https://github.com/GSA/federal-website-index/actions |
| Ingest federal website index  | tk                    | https://github.com/GSA/site-scanning-engine/blob/main/.github/workflows/ingest.yml          | https://github.com/GSA/site-scanning-engine/actions  |
| Enqueue websites for scanning | Daily at 12:10 AM UTC | https://github.com/GSA/site-scanning-engine/blob/main/.github/workflows/enqueue-scans.yml   | https://github.com/GSA/site-scanning-engine/actions  |
| Produce snapshots             | Sunday, 12 AM UTC     | https://github.com/GSA/site-scanning-engine/blob/main/.github/workflows/create-snapshot.yml | https://github.com/GSA/site-scanning-engine/actions  |

**Comment by akuny** [comment]
| action                                        | runs on               | specified in                                                                                        | manually run at                                       | description                                                                                                                                                                                                                                                                                                                                      |
| --------------------------------------------- | --------------------- | --------------------------------------------------------------------------------------------------- | ----------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| Build federal website index                   | Wednesday, 10 PM UTC  | https://github.com/GSA/federal-website-index/blob/main/.github/workflows/build-list.yml             | https://github.com/GSA/federal-website-index/actions  | This action builds the target URL list and saves it [here](https://github.com/GSA/federal-website-index/blob/main/data/site-scanning-target-url-list.csv), along with a file containing metadata about the list creation process [here](https://github.com/GSA/federal-website-index/blob/main/data/site-scanning-target-url-list-analysis.csv). |
| Analyze snapshot and target URL list analyses | Thursday, 10 PM UTC   | https://github.com/GSA/site-scanning-analysis/blob/main/.github/workflows/generate-all-analysis.yml | https://github.com/GSA/site-scanning-analysis/actions | This action creates three analysis reports in [this directory](https://github.com/GSA/site-scanning-analysis/tree/main/reports). These reports analyze: (1) the target URL list, (2) the primary snapshot that contains all live sites scanned, and (3) the "all" snapshot that contains all sites scanned.                                      |
| Ingest federal website index                  | tk                    | https://github.com/GSA/site-scanning-engine/blob/main/.github/workflows/ingest.yml                  | https://github.com/GSA/site-scanning-engine/actions   | This action prompts the scanning engine to ingest the target URL list, thereby updating the websites to be scanned, and removing invalid websites that are no longer present in the dataset.                                                                                                                                                     |
| Enqueue websites for scanning                 | Daily at 12:10 AM UTC | https://github.com/GSA/site-scanning-engine/blob/main/.github/workflows/enqueue-scans.yml           | https://github.com/GSA/site-scanning-engine/actions   | This action prompts the scanning engine to add every website to the scanning queue.                                                                                                                                                                                                                                                              |
| Produce snapshots                             | Sunday, 12 AM UTC     | https://github.com/GSA/site-scanning-engine/blob/main/.github/workflows/create-snapshot.yml         | https://github.com/GSA/site-scanning-engine/actions   | This action produces the CSV and JSON snapshots of the site scanning engine's most recent scan.                                                                                                                                                                                                                                                  |

**Comment by gbinal** [comment]
great work!  this is done.  I'll close it when we incorporate it into our documentation.

**Comment by gbinal** [comment]
done
