### ISSUE TITLE
possible bug with source fields

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#323]
For beta.tsp.gov, the bulk export seems to be suggesting that it is being sourced from the DAP list, but I don't see it there.  Rather, I see it in the pulse snapshot.  

Thoughts on what might be at issue?

**Comment by akuny** [comment]
The column order of the federal website index was out of alignment. That's now fixed: https://github.com/GSA/federal-website-index/commit/dec7a2305ef63dd8ecdf6c6d523209aec92195ea

**Comment by gbinal** [comment]
done
