### ISSUE TITLE
small updates to target URL list analysis report

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#324]
Following up on https://github.com/GSA/site-scanning/issues/302, two things come to mind: 
* In [the report](https://github.com/GSA/site-scanning-analysis/blob/main/reports/target-URL-list.csv#L2),  think that row 3 (`How many unique target urls are in the list?`) can be removed since it should always be the same as row 2, right? 
* There was one more field I think we were hoping for: "...the number of blank cells (excluding the agency code or bureau code columns) (should be zero, so finding a nonzero number would be helpful)."

**Comment by akuny** [comment]
These changes went live 11/21/22: see https://github.com/GSA/site-scanning-analysis/commit/d5ed24b474b0dcb3ba0b2d3ffa565fda6f25f4a8

**Comment by gbinal** [comment]
This is done.  

Sorry, but one more small change.  Can you reword `How many blank cells are there in the target URL list?` to be `How many blank cells are there in the target URL list (excluding the agency code, bureau, or bureau code columns)?`.

**Comment by gbinal** [comment]
done done!
