### ISSUE TITLE
change pulse snapshot location 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#326]
from [here](https://raw.githubusercontent.com/GSA/federal-website-index/main/data/snapshots/1-13-22/pulse-subdomains-snapshot-06-08-2020-https.csv) to [here](https://raw.githubusercontent.com/GSA/data/master/dotgov-websites/pulse-subdomains-snapshot-06-08-2020-https.csv).

**Comment by akuny** [comment]
Done as of 11/22/22.
