### ISSUE TITLE
redress the blank cells in the target URL list file 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#339]
Per [this report](https://github.com/GSA/site-scanning-analysis/blob/main/reports/target-URL-list.csv), there's apparently still some empty cells, when we think there shouldn't be.

**Comment by akuny** [comment]
The following base domains that appear in the target URL list do not appear in either the .gov or the pulse domain lists, so we don't have any agency or bureau information for them:

azdes.gov
ca.gov
csnet.gov
exis.gov
ftccomplaintassistant.gov
ga.gov
illinois.gov
in.gov
ky.gov
la.gov
maryland.gov
mt.gov
nc.gov
nd.gov
ne.gov
nv.gov
ocse.gov
ohio.gov
patientsafety.gov
ri.gov
sc.gov
sd.gov
sd.gov
tlab.gov
tn.gov
translate.goog
utah.gov
virginia.gov
vt.gov
wa.gov
wisconsin.gov
wisconsin.gov
wv.gov

The following base domains are sourced from `pulse-subdomains-snapshot-06-08-2020-https.csv` (https://raw.githubusercontent.com/GSA/data/master/dotgov-websites/pulse-subdomains-snapshot-06-08-2020-https.csv), which does not have a bureau column, so these base domains only have a corresponding agency:

ofda.gov
openinternet.gov
pentagon.gov
pracomment.gov
pregunteleakaren.gov
qart.gov
seniorcorps.gov
siteidiq.gov
stopfraud.gov
thecoolspot.gov
wgdp.gov

**Comment by gbinal** [comment]
Great work on this!  Thank you!  

Renaming this issue and then making it one for Lauren and me to fix.
