### ISSUE TITLE
MVP new snapshots to remove duplicate final URLs

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#355]
Make a spreadsheet of what would be impacted using different methodologies.  

the goal is to exclude duplicate final URLs, but also to know which one to exclude.  

Note that this is different than just excluding redirects

**Comment by gbinal** [comment]
In [this sheet,](https://docs.google.com/spreadsheets/d/141qCJ0elqlgupoCgqpVyxGn4WdjWsM_rChqKJMf0P7E/edit#gid=1103488585) we're trying to research how to dedup entries that have different final URLs but are on the same website.

**Comment by gbinal** [comment]
Final idea: 

Create two new snapshots: 

1st) Take the primary snapshot, and keep only one row whenever there are multiple rows with the same final URL.  Maybe called - `weekly-snapshot-unique-final-urls.csv`.  
  * Optional: At the same time, create a second file of the rows that are being excluded.  
  * Another idea - for cleanliness sake, have this file built _from_ the weekly-snapshot.csv file itself, not the DB.  

2nd)  Take the primary snapshot, and keep only one row whenever there are multiple rows with the same final URL.  *Then*, where multiple rows have the same final-url-website value, keep the one that has the shorter final URL.  Maybe called - `weekly-snapshot-unique-final-websites.csv`.  
  * Optional: At the same time, create a second file of the rows that are being excluded.  
  * Another idea - for cleanliness sake, have this file built _from_ the weekly-snapshot.csv file itself, not the DB.  

2nd)

**Comment by gbinal** [comment]
first pass at this [here](https://drive.google.com/drive/folders/1pFRD3s_wSU3HHhw8TmNHFzwIp6Xti1Jn?usp=sharing).

**Comment by gbinal** [comment]
we need to decide where to put that

**Comment by gbinal** [comment]
This'll go in the https://github.com/GSA/site-scanning-analysis repo

**Comment by akuny** [comment]
This has been added to the https://github.com/GSA/site-scanning-analysis repository. Here's a link to where the results are hosted: https://github.com/GSA/site-scanning-analysis/tree/main/unique_website_list/results

**Comment by gbinal** [comment]
Great work!  

Note to self, that this is run by the `Generate unique website list` action [here](https://github.com/GSA/site-scanning-analysis/actions).

**Comment by gbinal** [comment]
done!
