### ISSUE TITLE
reconfirm removal of non-federal websites 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#358]
It looks like our target URL list generator is missing one step.  It needs to remove non-federal domains, i.e. domains which are not on [this list](https://raw.githubusercontent.com/cisagov/dotgov-data/main/current-federal.csv).   

Right now, this step - I think - has been conflated with removing non-.gov urls (e.g. .mil, .com).  [Here's the relevant source code](https://github.com/GSA/federal-website-index/blob/main/builder/main.py#L173-L177), I believe.

**Comment by akuny** [comment]
Added this fix this morning. The new list of ignored non-gov URLs is here: https://github.com/GSA/federal-website-index/blob/main/data/snapshots/nonfederal-removed.csv
