### ISSUE TITLE
MVP a 'canonical url' scan

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#366]
e.g.: `<link href="https://18f.gsa.gov/join/" rel="canonical" />`

fieldname: `canonical_link`
data example: `https://18f.gsa.gov/join/`

location in snapshots - after `final_url_website` and before `final_url_mimetype`

**Comment by akuny** [comment]
The `canonical_link` field is now included in the snapshots.

**Comment by gbinal** [comment]
Here's some that appear to be missing when they shouldn't be (target URLs): 
* www.invasivespecies.gov
* jobs.irs.gov
* robottestmethods.nist.gov

**Comment by gbinal** [comment]
looks like those are solved and we're good to close this!
