### ISSUE TITLE
Expand the CMS scan's ability to detect 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#379]
Following up on the great work of #311, we should see if we can improve the metholodogy so as to detect more examples of CMS in action.  

To elaborate, we are looking for about 30 different snippets that would suggest different CMSes but are only seeing results for 4-5 CMS.  

Based on @benbalter's good work (summary [here](https://ben.balter.com/2021-analysis-of-federal-dotgov-domains/technologies/)), I would expect to see more CMSes represented.  Especially sharepoint, joomla, percussion, liferay maybe?  (source data [here](https://ben.balter.com/2021-analysis-of-federal-dotgov-domains/data.csv))

**Comment by akuny** [comment]
The scan engine has been updated to detect Microsoft Sharepoint via CMS headers--updated totals below.

<img width="208" alt="Screenshot 2023-06-02 at 1 10 26 PM" src="https://github.com/GSA/site-scanning/assets/13356991/e7a7f018-3b9f-4dcd-b9bb-11b082cb5f57">

**Comment by gbinal** [comment]
Great progress!!!!! 

For a next step, let's take this list, which Ben had previously been finding, and look at how his code looks for them, and if the method is HTML  or header sniffing, then to gutcheck whether there's any reason why we might not be seeing them.  

- Duda: 3 (0.45%)
- ExpressionEngine: 4 (0.6%)
- Joomla: 5 (0.76%)
- Kentico CMS: 1 (0.15%)
- Liferay: 2 (0.3%)
- MyWebsite: 3 (0.45%)
- Percussion: 9 (1.36%)
- SilverStripe: 1 (0.15%)
- Sitefinity: 2 (0.3%)
- Zendesk: 5 (0.76%)

**Comment by akuny** [comment]
Here's some info regarding the CMSs we're not picking up.

We currently don't have any HTML snippets or HTTP response headers to scan for the following CMSs:

- Duda: 3 (0.45%)
- ExpressionEngine: 4 (0.6%)
- Kentico CMS: 1 (0.15%)
- Liferay: 2 (0.3%)
- MyWebsite: 3 (0.45%)
- Sitefinity: 2 (0.3%)
- Zendesk: 5 (0.76%)

We are scanning for the following CMSs using the means specified below. If we have particular examples of sites that are using any one of these three CMSs, then I can try to determine why they aren't being picked up.

- Joomla: 5 (0.76%) - HTML and response header
- Percussion: 9 (1.36%) - HTML
- SilverStripe: 1 (0.15%) - HTML

**Comment by gbinal** [comment]
Gotcha.  So, for now, let's set aside the first 7 since we're not necessarily looking to further expand the detection methodologies.  

For the latter 3, yeah, let's look at Ben's data to see if the ones he's found are ones that we should have, too, or maybe they have changed CMSes.

**Comment by gbinal** [comment]
Note that if we expand the methodologies in the future, we should include wagtail CMS since that was requested.

**Comment by akuny** [comment]
For Joomla, Percussion, and SilverStripe, I think those are being detected in Ben's data by way of looking for a `meta` element with a generator attribute containing a certain value. In the case of dni.gov:

`<meta name="generator" content="Joomla! - Open Source Content Management">`

We currently are not looking for these elements, which is why we don't have hits for these three CMSs.

**Comment by gbinal** [comment]
Makes sense.  In our conversation, I think you said that we could pretty easily expand our html sniffing to cover those too, so that's the next step.

**Comment by gbinal** [comment]
this is done, in local development.  We can close it when the deploy is done and confirmed....

**Comment by akuny** [comment]
These changes are live and the snapshot has been updated.

**Comment by gbinal** [comment]
Great!

**Comment by gbinal** [comment]
this is done - great work.
