### ISSUE TITLE
Implement long term order

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#394]
template links [here](https://docs.google.com/spreadsheets/d/1CcLnKN5BlzfGsiuiktYb3RAcFUiWTGb3fF-g8FiegwI/edit#gid=1718921061) and [here](https://docs.google.com/document/d/1KIKQoYuhUpUysxdy-oIgSt5y5OGCKnKFHBo399kCu0k/edit)

**Comment by gbinal** [comment]
submitted

**Comment by gbinal** [comment]
Next steps are followup with K.K., and need to have P.A. finish budget approval

**Comment by gbinal** [comment]
updated document...

**Comment by laurenancona** [comment]
Karen recommended COR: new front ofc program analyst returns from PPL end of month: https://gsa-tts.slack.com/archives/C053FB9D788/p1682974180647999

**Comment by gbinal** [comment]
done!!!
