### ISSUE TITLE
collapse the dap parameter fields into one field/column

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#425]
specifically in the CSV

**Comment by gbinal** [comment]
Research has shown that this should be pretty doable so we're moving forward.

**Comment by akuny** [comment]
This change is live and the [CSV snapshots](https://digital.gov/guides/site-scanning/data/) now contain a single `dap_parameters_final_url` that in turn contains serialized JSON.

**Comment by gbinal** [comment]
done!!!
