### ISSUE TITLE
Address snapshot issue 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#426]

**Comment by akuny** [comment]
On Wednesday April 5a faulty federal-website-index target URL list was produced, and then ingested by the site scanning engine the next day per the schedule here: https://github.com/GSA/site-scanning-documentation/blob/main/pages/schedule.md

The fault in the federal-website-index list builder has been fixed and the snapshot is back up.

**Comment by gbinal** [comment]
thanks!
