### ISSUE TITLE
Iterate required link scans

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#432]
Right now, we are scanning for: `foia`, `about`, `usa.gov`, and `privacy`.  

Based on feedback in #430, I think we should add the following terms: `fear`, `inspector`.  

While we're at this, let's rename this field from `required_links` to `required_links_url`.  

-----

I _wish_ we could in a separate field scan (called required_links_text) for the following in the hyperlinked text itself: `about us`, `accessibility`, `budget and performance`, `no fear act`, `foia`, `freedom of information act`, `privacy policy`, `inspector general`, and `vulnerability disclosure`.  

-----

These fields will go in this order in the CSV and elsewhere:  

* cloud.gov pages
* required_links_url
* required_links_text
* uswds_favicon

**Comment by gbinal** [comment]
great work - I do have one change I'd like to requesat though, and that is for the actual `required_links_text` results to be the same, exact strings that are being found.  So, returning in the data `privacy policy`, not `privacy` and `vulnerability disclosure` not `vulnerability`.

**Comment by akuny** [comment]
Thank you for the feedback--those changes were deployed on 4/24/23: https://github.com/GSA/site-scanning-engine/pull/242

**Comment by gbinal** [comment]
done!
