### ISSUE TITLE
Fix Federal Website Index List Building GitHub Action

### ISSUE THREAD

**Issue by akuny** [GSA/site-scanning#445]
When the build script for the [federal website index](https://github.com/GSA/federal-website-index) runs by way of a GitHub Action, it results in a final list that comprises only ~6,000 websites instead of the ~27,000 expected websites. Running the script locally works as expected.

**Comment by akuny** [comment]
After refactoring the manner in which base domain, agency, and bureau data is merged into the final URL list, the script is now working as expected locally and when hosted.

**Comment by gbinal** [comment]
great work!!
