### ISSUE TITLE
Research how to detect HTTPS support 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#453]
As a followup to #439 and #452, we may stop getting `invalid_ssl_cert` errors.  

1) Look at the data after #452 is done, but then...
2) Think about new ways we could capture that information

**Comment by gbinal** [comment]
Specifically, we want to detect: 
* https enforced 
* hsts preloading

**Comment by laurenancona** [comment]
draft guidance:
"Agencies shall encrypt all web traffic across their websites and digital services as HTTPS, including both public-facing (internet-facing) and internal facing traffic. Agencies shall "preload" all their registered .gov or .mil domains as HTTPS-only in modern web browsers."

**Comment by gbinal** [comment]
done!
