### ISSUE TITLE
MVP a site search scan 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#464]
there's two ways to do this, I think - detecting search boxes and searching for search providers.  It could also be a hybrid of the two (e.g. detecting a search.gov snippet is one of the ways of detecting a box).  

Hopefully, we could include in an MVP at least 2-3 of these: search.gov, bing, google programmable search engine, solr, drupal, wordpress.  Of those, only search.gov is critical.  

Examples of site search:

search.gov
* www.gsa.gov
* www.digital.gov
* www.state.gov

???
* https://www.fbi.gov/

Possible snippets? 
* `usa-search`
* [ note - check out the search.gov [implementation instructions here](https://search.gov/get-started/go-live.html), too]
* [note - look at the common CMS solutions, e.g. drupal, wordpress for examples of those sites to find]

More notes: 
* https://slashdot.org/software/site-search/

**Comment by gbinal** [comment]
The MVP as you've designed it so far is great, @akuny.  Let's ship it.  

To confirm, it will look for the string `search` anywhere in an `id`, `class`, or `action` attribute within an `input` or `form` element.  If it detects one, then the result will be `TRUE`.  If not, `FALSE`.  

It can go after login_detected in the CSV.

**Comment by akuny** [comment]
This is live and the snapshot has been updated.

**Comment by gbinal** [comment]
great work!
