### ISSUE TITLE
MVP Scan for login options 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#477]
Search the url of every hyperlink on each page for each of the strings: `id.me`, `login.gov`

field name: login_provider
Located: after 3rd party count and before login_detected

To followup, after we have test data, book 30 min.

**Comment by gbinal** [comment]
to clarify though, the MVP can just be local code and a single scan

**Comment by gbinal** [comment]
update:  

This should either be two fields using the exact same methodology as the required links scans (though with the same strings in both cases: `id.me` and `login.gov` - names login_provider_url and login_provider_link), OR it can be one field that indicates if either of those strings appear in either the hyperlinked text or the hyperlink URL

**Comment by gbinal** [comment]
update 2: as I wrote that second option, in the previous program, I realized that it would actually be simpler to just search anywhere inside the `<a>` tags!  That would be fine, too.

**Comment by akuny** [comment]
The login scan has been updated to check both anchor tag's enclosed text and href attributes for the strings "id.me" and "login.gov". Here's the relevant code:

https://github.com/GSA/site-scanning-engine/blob/main/libs/core-scanner/src/scans/login.ts

This update has been deployed, the scans have run, and the snapshot is updated. 162 records have data in the new `login_provider` field.

**Comment by gbinal** [comment]
awesome - thanks so much!!  

Sorry, but as we just decided, let's expand it to be everything inside the <a> tags.

**Comment by gbinal** [comment]
done.  great work, @akuny !!!
