### ISSUE TITLE
Google Apps Script is working correctly in the API Import Template (Google Sheet)

### ISSUE THREAD

**Issue by laurenancona** [GSA/site-scanning#48]
There's a function in the [Google Sheet Template](https://docs.google.com/spreadsheets/d/171q7B-1X_gDfv_9VKiPu8K4j5KYaAfh90u1Vl6JMzfU/edit#gid=1937835393) that uses a[ Google Script](https://script.google.com/home/projects/1uQ_dIn-uC4HTAa0yojoXLSpy2RA88k53Spwy1UC_GHKYG0foQCp7duvA/edit) to pull in the API key within a `while` loop and I could use a set of dev eyes to help debug. 

The loop function as written is hitting the Google Scripts limit and timing out after 30 seconds.

**Comment by gbinal** [comment]
this involves https://site-scanning.api.data.gov/

**Comment by gbinal** [comment]
Closing this issue while the query builder is on hold.  We can reopen when the time comes.
