### ISSUE TITLE
add .mil sites

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#486]
https://www.web.dma.mil/Our-Customers/#department-of-defense-websites

**Comment by gbinal** [comment]
possibly also then add a new field for TLD

but exclude .edu, etc. on that list

**Comment by gbinal** [comment]
don't include in the current snapshots
note that someone needs to reach out to DOD to tell them

**Comment by gbinal** [comment]
snapshot of links is here - https://github.com/GSA/federal-website-index/blob/main/data/dataset/DOD-websites-8-29-23.csv  

We should discuss the best way to integrate this.  I think that the easiest path would be to append it to the federal website index at it's last step of creation.  

Somewhat more pure might be to treat that file as just another source dataset at the first stage of creating the index, but we'll then need to figure out how to not filter out the .mil sites at [narrowing stage 3](https://github.com/GSA/site-scanning-documentation/blob/main/pages/index_narrowing_steps.md).  

We'll also need to think about how to best populate the agency/bureau/branch/etc fields.  

For convenience, [here's](https://docs.google.com/spreadsheets/u/2/d/1BYGJpdhy5Vc63NSzFuWzYfwi7yapmlXrMj1wQxyLt3U/edit#gid=0) the google sheet I'm updating.

**Comment by gbinal** [comment]
Wait, also note: 

https://www.defense.gov/Resources/Military-Departments/DOD-Websites/

**Comment by laurenancona** [comment]
I'm adding ^ that list of ~500 to a new tab in the google sheet

**Comment by gbinal** [comment]
For next steps: 
* Andy will re-familiarize himself with the index creation process
* Gray will think through how to handle agencies and bureaus
* Lauren will look at adding to the .mil list

**Comment by gbinal** [comment]
For next , next steps: 
* Gray to create the two necessary files (and remove extraneous content from the .mil list, including `/`)
* Gray to better document and affirm the work for next sprint

**Comment by gbinal** [comment]
alright - I've prepped the new files but we should talk through what makes the most sense, re: adding in bureaus.

**Comment by gbinal** [comment]
Alright - here's the two files.  

https://github.com/GSA/federal-website-index/blob/main/data/dataset/dotmil_websites.csv
https://github.com/GSA/federal-website-index/blob/main/data/dataset/dotmil_domains.csv

**Comment by gbinal** [comment]
@akuny - note that I just updated the following file to include branch info 

https://github.com/GSA/federal-website-index/blob/main/data/dataset/dotmil_websites.csv

**Comment by gbinal** [comment]
Results of initial scans - https://docs.google.com/spreadsheets/d/1PqPp5SZDoup8HEesqCm8yKIdpS3Pg8bgDoAzIT7EbVs/edit#gid=1423348741

**Comment by gbinal** [comment]
This is live in production.  Great work, @akuny !!
