### ISSUE TITLE
research ultra long cells

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#495]
A few rows in our snapshots have cells that are very, very long - possibly to the point of breaking the CSV when uploading into some programs.  It looks like the issue is likely with the sitemaps.  We should research if this is causing problems anywhere and weigh whether to truncate those cells.

**Comment by gbinal** [comment]
As an initial stab at addressing this, we're going to institute a 5,000 character limit to each cell.

**Comment by gbinal** [comment]
Looks like somehow longer cells are still coming through, [example file](https://docs.google.com/spreadsheets/d/19Ag-cYPSiMfZiOW3O5yK5MYnxXOfYDRci4swMCxbwWQ/edit#gid=100890759) - e.g. orsbloodtool.sandia.gov.

**Comment by akuny** [comment]
As discussed yesterday afternoon, a 2,000 character limit is now in place for the CSV snapshot.

**Comment by gbinal** [comment]
hooray!!!!
