### ISSUE TITLE
Prototype agency DAP and USWDS report

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#498]
Consuming the Unique Final Website [Snapshot](https://raw.githubusercontent.com/GSA/site-scanning-analysis/main/unique_website_list/results/weekly-snapshot-unique-final-websites.csv), make a weekly report a la [this](https://github.com/GSA/site-scanning-analysis/blob/main/reports/drafts/dap-report-1.csv)

It should live [here](https://github.com/GSA/site-scanning-analysis/tree/main/reports), and be called idea.csv

And run Tuesday, 12am UTC.  (please update [this](https://github.com/GSA/site-scanning-documentation/blob/main/pages/schedule.md))

**Comment by akuny** [comment]
This report is live and the schedule has been updated.

**Comment by gbinal** [comment]
https://github.com/GSA/site-scanning-analysis/blob/main/reports/idea.csv

Looks great.  Thank you!!!!
