### ISSUE TITLE
draft a diagram of data flow for the website index

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#501]

**Comment by laurenancona** [comment]
[Federal Website Index - ETL Process.pdf](https://github.com/GSA/site-scanning/files/12175476/Federal.Website.Index.-.ETL.Process.pdf)

**Comment by laurenancona** [comment]
![Federal Website Index - ETL Process](https://github.com/GSA/site-scanning/assets/2152151/fa6f0729-0126-456e-8597-7ccf3dd291b8)

**Comment by gbinal** [comment]
great!  hosted here - https://github.com/GSA/site-scanning-documentation/blob/main/about/Federal.Website.Index.-.ETL.Process.pdf
