### ISSUE TITLE
Discuss /cisa-gov/dotgov-data/

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#54]
Now that https://github.com/cisagov/dotgov-data/ is set up, let's discuss if we want to keep using that repo for the purposes we have in the past or if we want to move some/all of those over to /gsa/federal-websites-index/.

**Comment by laurenancona** [comment]
Make a PR to tidy up content in CISA repo that are "ours" and don't need to live there.

**Comment by gbinal** [comment]
done!
