### ISSUE TITLE
prototype recipe for joining DAP data

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#542]
And consider adding as fields 1 or 3 or more 9 directly into the data

one other option to weigh is creating a new github action that generates a snapshot (though weigh then how much people might want to do this with the smaller snapshots)

**Comment by gbinal** [comment]
done!

**Comment by laurenancona** [comment]
Working example: https://docs.google.com/spreadsheets/d/1Vks4mcIWrErbZyb951uXiHi6xVSo3DA3ctHJLBcsoto/edit#gid=799262178
