### ISSUE TITLE
Request edits to the domain export 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#55]
There's various errors and inconsistencies in the [federal domain dataset](https://github.com/cisagov/dotgov-data/blob/main/current-federal.csv) and I've filed an [issue](https://github.com/cisagov/dotgov-data/issues/8) asking how we could fix those.  

When we get an answer, it'd be good to request some fixes.

**Comment by laurenancona** [comment]
Cameron had some clarifying questions on this [issue](https://github.com/cisagov/dotgov-data/issues/8#issuecomment-858894545)
