### ISSUE TITLE
filter out non-websites

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#557]
As part of creating the primary snapshot, also filter out entries that have a final_url_mimetype of: 
* application/xhtml+xml
* application/xml
* application/json
* text/xml

**Comment by akuny** [comment]
This change has been deployed and the snapshot has been updated.

**Comment by gbinal** [comment]
great work!  I'm going to leave this open while I update the documentation.

**Comment by gbinal** [comment]
alright - documentation updated.  closing
