### ISSUE TITLE
change 2 IDEA reports to semantic version

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#561]
Instead of public sans font, let's make the USWDS metric we use whether or not there's a semantic version detected.  

the headers should say USWDS Semantic Version instead of USWDS Font.

**Comment by gbinal** [comment]
Specifically, these are the two reports to change - 

https://github.com/GSA/site-scanning-analysis/blob/main/reports/idea.csv
https://github.com/GSA/site-scanning-analysis/blob/main/reports/idea-bureau.csv

**Comment by akuny** [comment]
These two reports have been updated.

**Comment by gbinal** [comment]
great work!  I'll let our interested colleagues know and then close this issue!
