### ISSUE TITLE
expand dap detection status to include if certain parameters are included

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#587]
There are 250 entries that are dap=false, but have parameters that suggest that dap should be true.  All but 2 of those parameters include `"agency"`.  I think we should modify the dap status to include those.  

[Here's](https://docs.google.com/spreadsheets/d/1jKN-iF7Cd9X34Frzo160SxUBmsuQhgOpetrZu4gPRlM/edit#gid=279609490) a snapshot file where I've filtered for these.

**Comment by gbinal** [comment]
this is done.  Woo!!!

**Comment by gbinal** [comment]
alas, it looks to me like maybe this isn't implementing yet.  reopening...

**Comment by akuny** [comment]
I can confirm that based on the snapshot updated this morning, this issue is now resolved.

**Comment by gbinal** [comment]
rock - thank you!
