### ISSUE TITLE
Sketch out the months of July/August (a.k.a. the rest of summer)

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#61]
* Important:
  * Closed all of the loops with our stakeholders 
  * Try to complete the creation of the new website index 
  * Polish and round out the web presence 
    * Copy-editing 
    * Checking links 
    * Resolve the Spreadsheet
    * Flesh out documentation repos
    * Review on mobile
  * Plan timing with Alex
    * Put in the staffing issue, asking for 2 months full time, starting after Oct., along [these lines](https://github.com/18F/staffing/issues/755)
  * Ensure engine is now running reliably

**Comment by laurenancona** [comment]
Closing because we did this :)
