### ISSUE TITLE
How to get a .gov site added to Site Scanner?

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/site-scanning#62]
### Story

As a federal website owner,
I want to make a .gov URL discoverable to Site Scanner,
So I can access the valuable output that Site Scanner provides

### Draft acceptance criteria

Given I have a live .gov URL that is not returning a result in Site Scanner API
When I make a request to the Site Scanner team or app
Then I receive a response from the team or application acknowledging/confirming the request
AND I am subsequently able to access results for the requested URL via the Site Scanner API

---

An example of a .gov URL that I'd like to make discoverable: https://touchpoints.digital.gov.

**Comment by mvogelgesang** [comment]
Additional GSA URLs to be added. At a glance, some are employing DAP while others are not. 

- 8astars.fas.gsa.gov
- amp.fas.gsa.gov
- app.cloud.gov
- beta.SAM.gov
- cdo.gov
- conectate.gobiernousa.gov
- courtsweb.gsa.gov
- cpars.gov
- derisking-guide.18f.gov
- design.login.gov
- engineering.18f.gov
- federalist-builder.18f.gov
- files.18f.gov
- inventory.data.gov
- opd.gsa.gov
- p3.cap.gsa.gov/gui
- partners.login.gov
- playbook.cio.gov
- playbooks.idmanagement.gov
- portfolios.18f.gov
- saferfederalworkforce.gov
- sam-landing.login.gov
- tmf.cio.gov
- tophealth.pif.gov
- touchpoints.digital.gov
- travel.reporting.gov
- vaadvantage.gsa.gov
- wp-bsp.data.gov
- digitalcorps.gsa.gov
- odp.gsa.gov
- itvmo.gsa.gov

**Comment by gbinal** [comment]
Closing this issue out - we 1) ensured all of these sites were in the federal website index  a while back, but also 2) added a process for manually adding missing websites to the index in the future, too

**Comment by ryanwoldatwork** [comment]
Hi @gbinal,

Can you share a link or more info related to the process for adding websites to the index?
