### ISSUE TITLE
Review data dictionary

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#654]
Weigh: 
* Rewording the field names 
* Rewording the field IDs
* order and grouping of fields in the data dictionary
* and thus, order of the fields in the CSV
* (any norms about prefixes in the field ids we want to make)
* (adding or removing 'final_url' from field names or ids or descriptions)

**Comment by gbinal** [comment]
Question - should we add a new column for the prefix info?

**Comment by gbinal** [comment]
Work in progress [here](https://github.com/GSA/site-scanning-documentation/blob/dictionary-work/data/Site_Scanning_Data_Dictionary.csv). [PR](https://github.com/GSA/site-scanning-documentation/pull/12).

**Comment by gbinal** [comment]
Questions - 
* ask andy if cookies are only third party or no?  If so, maybe we call it third party - cookie domains?  
* idea - privacy instead of third party? 
* consider a category column  before all of this, e.g. with infrastructure, SEO, what else?

**Comment by gbinal** [comment]
More:

| current | proposed | 
| -- | -- |
|  Infrastructure - Cookies	| Infrastructure - Cookie Domains |


Questions: 

For the robots.txt and sitemap.xml fields, is it necessary to include Final URL?  And/or is that correct (vs. Target URL)?

Next, let's weigh these field ID changes:  

| current | proposed |
|  -- |  -- |
| dns_ipv6 | ipv6|
| dns_hostname	 | hostname |
| login_detected	 | login |
| search_detected  |  site_search	|
|  dap_detected_final_url	 |  dap_detected	|
| dap_parameters_final_url	 |  dap_parameters	|
| og_article_published_final_url	 | og_article_published |
|  og_article_modified_final_url	| og_article_modified |
| og_title_final_url |  og_title |
|  og_description_final_url	 |  og_description	|
|   main_element_present_final_url	 | main_element_present	|
|  | |
|  | |
|  | |
|  | |

**Comment by laurenancona** [comment]
my only suggest is formatting:
Count of URLs in the detected `sitemap.xml`

**Comment by gbinal** [comment]
[New PR](https://github.com/GSA/site-scanning-documentation/pull/13) since old one had conflicts.  

Still outstanding .... 

- Is final url - status code the same as what I would see if I just loaded the final URL directly?
- Do 202 codes work?
- media type 
- lots of field ids 

- For the robots.txt and sitemap.xml fields, is it necessary to include Final URL? And/or is that correct (vs. Target URL)?
- Is the robots.txt Final URL live and does it end with robots.txt? - is this the best metric
- Reweigh use of Final URL and Target URL in the sitemaps/robots fields.

**Comment by gbinal** [comment]
done
