### ISSUE TITLE
Possible bug with final url TLD field 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#660]
There's a couple dozen rows where there's no final url but the final URL top level domain is populated (usually with .io).  Any thoughts on why this is happening?  Here's a [sheet](https://docs.google.com/spreadsheets/d/1nETdUvxkVB723U5wjNpOAdfPwlPuuYkgado8mpWncJQ/edit#gid=1133420646) with data that shows this.  

![Screenshot 2023-11-01 1 23 06 PM](https://github.com/GSA/site-scanning/assets/633088/83c8e5f6-4a44-4068-8e0c-e6cea73f95da)

**Comment by akuny** [comment]
This has been fixed: https://github.com/GSA/site-scanning-engine/pull/285

Root cause: previous scans succeeded, so there was a `final_url` value, but the module updating core results was not set to explicitly set `final_url_top_level_domain` to `null` if subsequent scans failed.

**Comment by gbinal** [comment]
great - thanks!
