### ISSUE TITLE
bug: strange mimetype

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#661]
Looks like this came back.  In this [file](https://docs.google.com/spreadsheets/d/1nETdUvxkVB723U5wjNpOAdfPwlPuuYkgado8mpWncJQ/edit#gid=1133420646), I'm notice that one entry had a strange mimetype:  g5nr.nccs.nasa.gov

Turns out though that it's not just in the CSV, it's also in the API - https://api.gsa.gov/technology/site-scanning/v1/websites/g5nr.nccs.nasa.gov?API_KEY=DEMO_KEY

p.s.  I _think_ that's the same one that gave us fits a few months ago.  

![Screenshot 2023-11-01 1 29 39 PM](https://github.com/GSA/site-scanning/assets/633088/45f34edb-dcad-41a1-894f-036a6f5d7d0a)

![Screenshot 2023-11-01 1 29 10 PM](https://github.com/GSA/site-scanning/assets/633088/00ef72c3-7e62-46db-afd6-6f75425f100d)

**Comment by akuny** [comment]
Believe it or not, this weird MIME type appears to be coming from the server for this URL. Here's a screenshot of a GET request to this URL made via Postman: same weird MIME type appears there:

![image](https://github.com/GSA/site-scanning/assets/13356991/097e9f76-d5f7-45e4-9960-6c80782479ae)

**Comment by gbinal** [comment]
wow - okay!  Well, I guess that's that then.
