### ISSUE TITLE
edit the new viewport meta field

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#662]
* Reword the field id  to be `viewport_meta_tag`
* Move the field to after `third_party_service_count` and before `cookie_domains`
* Go ahead and activate that field in the API and CSV

**Comment by akuny** [comment]
These changes are live: see https://github.com/GSA/site-scanning-engine/pull/286 for details.

**Comment by akuny** [comment]
Heads-up, the scanner is running right now so the snapshot and API will be updated later today.

**Comment by gbinal** [comment]
thanks!
