### ISSUE TITLE
Consider GitHub Actions for the producer

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#67]
The original engineer later reflected that the role of the producer could possibly be phased out entirely by using GitHub Actions.  He suggested that doing this would simplify and make more robust the system.  

Let's consider that idea and weigh implementing it.

**Comment by danielnaab** [comment]
I agree on this one and suggest we prioritize it, as the benefits will help with some some other issues.

1) Provides an interface to manually spawn jobs (via CLI or the Github Actions web interface)
1) Frees up RAM in the cloud.gov space
1) Simplifies the deployment

**Comment by gbinal** [comment]
This is awesome.  Great work.

**Comment by gbinal** [comment]
(For convenience, [the link for these](https://github.com/GSA/site-scanning-engine/actions/workflows/clear-queue.yml).)
