### ISSUE TITLE
update API and snapshot field names and order 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#704]
Reorder the CSV to match the [new order of fields](https://github.com/GSA/site-scanning-documentation/blob/data-dictionary-2/data/Site_Scanning_Data_Dictionary.csv) in the data dictionary 

change the following field IDs in the API and static files (CSV and JSON, including the various sub-snapshots):

| current | proposed |
|  -- |  -- |
| dns_ipv6 | ipv6|
| dns_hostname	 | hostname |
| login_detected	 | login |
| search_detected  |  site_search	|
| searchgov | search_dot_gov |
|  dap_detected_final_url	 |  dap	|
| dap_parameters_final_url	 |  dap_parameters	|
| og_article_published_final_url	 | og_article_published |
|  og_article_modified_final_url	| og_article_modified |
| og_title_final_url |  og_title |
|  og_description_final_url	 |  og_description	|
|   main_element_present_final_url	 | main_element_present	|
|  final_url_mimetype	 | final_url_media_type |
| robots_txt_final_url_mimetype | robots_txt_final_url_media_type |
| robots_txt_final_url_filesize_in_bytes	| robots_txt_final_url_filesize |
| sitemap_xml_final_url_mimetype	 | sitemap_xml_final_url_media_type  |
| sitemap_xml_final_url_filesize_in_bytes	| sitemap_xml_final_url_filesize	|

**Comment by gbinal** [comment]
Alright - notice has gone out.  We're good to make these changes on January 31.

**Comment by akuny** [comment]
The site scanning engine now produces a snapshots using the new names above and the order specified in the data dictionary. The API also reflects these changes.

The site scanning analysis reports have also been updated to reflect these changes: https://github.com/GSA/site-scanning-analysis/pull/4

**Comment by gbinal** [comment]
Great work and good call on the reports!
