### ISSUE TITLE
Create by-agency slicer of the bulk data

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#710]
In [this directory](https://github.com/GSA/site-scanning-snapshots/tree/main/snapshots), create a folder named 'By Agency', and generate each week, individual CSV files that are each  the slide of the [Primary snapshot](https://api.gsa.gov/technology/site-scanning/data/weekly-snapshot.csv), but for each agency.  

* This should be a distinct github action.  
* filenames should be: full_agency_name_as_used_in_this_field.csv (field = target_url_agency_owner).
* According to the [primary snapshot analysis report](https://github.com/GSA/site-scanning-analysis/blob/main/reports/snapshot-primary.csv), there should then be about 151 reports.  
* The by agency snapshots should be generated each week on Monday, 12 AM UTC.  
* Each by agency snapshot will still need the header row.  
* The files should be overwritten each week.  
* If an agency goes away, there's no need to remove the file unless it's easier for it to be.

**Comment by akuny** [comment]
Agency slices of snapshot data are now here: https://github.com/GSA/site-scanning-snapshots/tree/main/by_agency

These will be updated every Monday at 12am UTC.

**Comment by gbinal** [comment]
Great work!  

I'm going to leave this open until we share it with OMB and update our documentation but it looks great.

**Comment by gbinal** [comment]
done
