### ISSUE TITLE
Confirm if our scans are able to follow meta redirects

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#712]
discuss afresh if not

**Comment by akuny** [comment]
In the primary scan, the puppeteer Page object passed to the scan is used to retrieve a response as such:

```
  const response = await page.goto(url, {
    waitUntil: 'networkidle2',
  });
```

`waitUntil` defines a condition to wait for before considering the navigation to be finished. Passing `networkidle2` here instructs Puppeteer waits until there are no more than 2 network connections for at least 500 ms. 

If a meta refresh is set to trigger after a short interval, and the network becomes idle (that is, no more than 2 network connections for at least 500 ms) before the refresh happens, `page.goto` may resolve before the meta refresh redirects the page. It varies case by case and is tricky to nail down. 

There is a `page.waitForNavigation()` method that forces Puppeteer to wait for all navigation to resolve, but this adds a considerable amount of runtime to each individual scan.

**Comment by gbinal** [comment]
This is great - thanks!  Creating a new issue with next steps (#724)
