### ISSUE TITLE
change canonical target URL list location

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#72]
Currently, the system looks to [this location](https://raw.githubusercontent.com/GSA/data/master/dotgov-websites/site-scanning/current-federal-subdomains.csv) (edited [here](https://github.com/GSA/data/blob/master/dotgov-websites/site-scanning/current-federal-subdomains.csv))for the target URL list it needs to import (see [code](https://github.com/GSA/site-scanning-engine/blob/main/libs/ingest/src/ingest.service.ts#L20)).  

We should change it to [this location](https://github.com/GSA/federal-website-index/raw/main/data/site-scanning-target-url-list.csv) (edited [here](https://github.com/GSA/federal-website-index/blob/main/data/site-scanning-target-url-list.csv)).  

(Note - [here's a duplicate location](https://github.com/cisagov/dotgov-data/blob/main/dotgov-websites/site-scanning/current-federal-subdomains.csv) that has never been in use and can be deleted)

**Comment by danielnaab** [comment]
@gbinal @laurenancona The new CSV has a bunch of junk at the end of the file, lines with: `,,---,#N/A,#N/A,,,`

**Comment by gbinal** [comment]
ah, thank you!  fixing [here](https://github.com/GSA/federal-website-index/pull/16).

**Comment by gbinal** [comment]
done with [this](https://github.com/GSA/site-scanning-engine/pull/132)
