### ISSUE TITLE
MVP SEO scans and scan updates 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#730]
- text within <title></title>
- text within the content attribute of the element ([link](https://developer.chrome.com/docs/lighthouse/seo/meta-description/))
- meta tags: article:published_time
- meta tags: article:modified_time
- content within hreflang attributes (may be more than one, and note different links) ([link](https://developer.chrome.com/docs/lighthouse/seo/hreflang/))
- editing the canonical urls scan to also look in the header of the html response ([link](https://developer.chrome.com/docs/lighthouse/seo/canonical/))

**Comment by gbinal** [comment]
Actually, all of this is TBD.  

Field ids would be: 
* page_title
* TBD

**Comment by akuny** [comment]
FWIW we're already scanning for these two:

- meta tags: article:published_time
- meta tags: article:modified_time

See https://github.com/GSA/site-scanning-documentation/blob/main/data/Site_Scanning_Data_Dictionary.csv lines 43 and 44.

**Comment by akuny** [comment]
Disregard the comment above. I misunderstood the requirement.

**Comment by gbinal** [comment]
Note and weigh: 
1) keywords/tags 
2) https://search.gov/indexing/metadata.html#crawling-metadata

**Comment by gbinal** [comment]
done
