### ISSUE TITLE
MVP 2 performance metrics 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#734]
- Largest Contentful Paint (LCP): measures loading performance. To provide a good user experience, LCP should occur within 2.5 seconds of when the page first starts loading.
- Cumulative Layout Shift (CLS): measures visual stability. To provide a good user experience, pages should maintain a CLS of 0.1. or less.

**Comment by gbinal** [comment]
Great work, @akuny !!  Initial data [here](https://docs.google.com/spreadsheets/d/1utSVWP3MnxcpW5HvMqQR1126jaF9hDbfLcNxRB7oYD8/edit#gid=65640199) for us to explore and play with.  

Next, we need to affirm the field-ids and order within the data dictionary, then gut check further that the data seems to make sense.  After that, we'll launch.

**Comment by gbinal** [comment]
Proposal:  

- Make them a new category in the data dictionary - `Performance`.  
- Field ids of `largest_contentful_paint` and `cumulative_layout_shift`.
- That they go after the viewport result and before the required links results, in alphabetical order (so cls then lcp).

**Comment by akuny** [comment]
I can confirm that both CLS and LCP are measured in milliseconds.

**Comment by akuny** [comment]
These two new fields are now included in the snapshots and the API.

**Comment by gbinal** [comment]
Great work!
