### ISSUE TITLE
Prototype new ingest process for new public yes/no field 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#775]
Canonical list 
public yes/no 

Gray and Lauren will take the first pass at sketching this out and then will work with Andy to try and implement it.

**Comment by gbinal** [comment]
Initial draft file [here](https://github.com/GSA/federal-website-index/blob/main/data/dataset/omb_idea.csv).  

But what I realized is that we should drop the column for omb-canonical and instead make it a source.

**Comment by gbinal** [comment]
Ideas include - adding in this data to the federal website index file, or running a separate process to overwrite a column of data in the database, lining up Websites to Target URL.  

field_id - `public` - results would be True/False.

**Comment by akuny** [comment]
I've included an "ombIdeaPublic" field in the scan engine's website entity that is updated with true or false when the ingest process runs. Right now this field is not public facing in the API or the snapshots, but we can use it to create more granular snapshots and/or make it public and/or queryable. https://github.com/GSA/site-scanning-engine/pull/304

**Comment by gbinal** [comment]
Great!  I do think that when you are back, we'll want to actually keep the field_id of `public` (though we did talk about it and weighed `ombIdeaPublic` heavily).

**Comment by gbinal** [comment]
Let's place it after `Target URL - Data Source` and before `Scan Status - Date`
