### ISSUE TITLE
check performance with a larger target list

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#79]
Followup to #32 

Check back later to see how the system did with the new list. Criteria: Whether the full target URL list was scanned (as opposed to the system hanging before getting to the end of the list); if the proportion of fields that are missing or erroneous has gone up dramatically.

**Comment by laurenancona** [comment]
Close after new Target URL list is correctly being scanned completely

**Comment by gbinal** [comment]
duplicative
