### ISSUE TITLE
process USDA website notes 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#798]
From 2-6-24 email 

Asa1-evpnwest.usda.gov
Asa2-evpnwest.usda.gov
Asa3-evpnwest.usda.gov
Nag.edc.usda.gov
Asa1-evpneast.usda.gov
Asa2-evpneast.usda.gov
Asa3-evpneast.usda.gov
Evpneast.usda.gov
Evpn.usda.gov
Certevpn.usda.gov
 

This domain is retired:

srs.fs.usda.gov (looks like it is redirecting to the correct sub-site but the top level is not listed – see below)
 

Missing the Forest Service web presence (our two big sites):

fs.usda.gov
fs.usda.gov/research (this is not a sub-page it’s a separate website using the same domain structure)

**Comment by laurenancona** [comment]
Andrew's asked for a quick QA on this once we figure it out:
"How does SS detect DAp on websites, and in cases where agency uses GTM or self-hosts?"

**Comment by gbinal** [comment]
done
