### ISSUE TITLE
Expand DAP scans 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#855]
By also scanning for this tag: `G-CSLL4ZEK4L`

**Comment by akuny** [comment]
This change has been merged into main: https://github.com/GSA/site-scanning-engine/commit/c55ae85d05f579915d4503a14009490d1827d155

Later today, we'll redeploy and have updated scan results by tomorrow.

**Comment by gbinal** [comment]
Rock.   Thanks!

Note to self to doublecheck marketplace.fedramp.gov next week to see.
