### ISSUE TITLE
Clarification to the `public` field 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#860]
When [this file](https://github.com/GSA/federal-website-index/blob/main/data/dataset/omb_idea.csv) is consumed, Target URLs that have `Public-Facing=Yes` should result in `public=TRUE`; Target URLs that have `Public-Facing=No` should result in `public=FALSE`; and Target URLs that aren't represented in [that file](https://github.com/GSA/federal-website-index/blob/main/data/dataset/omb_idea.csv) should have the `public` field empty or null.

**Comment by gbinal** [comment]
this is done.  

note that if a row in the omb-idea seed list is empty or has another value than yes/no, the result will be that field being empty in the snapshot

**Comment by akuny** [comment]
The snapshots are now updated to reflect these changes to the federal website index.

**Comment by gbinal** [comment]
great work - I'm seeing it in production.  thanks!
