### ISSUE TITLE
Add two scan status indicators  

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#863]
Or, something in the data to differentiate between no errors and scan didn't run.  

Decided:  We should add data fields for the a11y and performance scan statuses. 

* accessibility_scan_status - after primary scan status and before dns scan status 
* performance_scan_status - after not found scan status and before robots_txt scan status

**Comment by akuny** [comment]
These two fields are now exposed in the snapshots and the API.

**Comment by gbinal** [comment]
woo!  good work
