### ISSUE TITLE
prune 5 details fields from a11y details file 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#880]
- Impact - This field is good perspective, but isn't critical.  
- Help - Content in this field is duplicative with Description 
- Failure Summary - Content in this field is duplicative with Description 
- Target - Content in this field is redundant with that in the HTML field
- Data - Content in this field is duplicative with Message

**Comment by akuny** [comment]
These changes are deployed and the scanner will re-run tonight for a fresh export tomorrow 3/28/24.

**Comment by gbinal** [comment]
rock!

**Comment by gbinal** [comment]
Closing but will keep #881 open until done.

**Comment by gbinal** [comment]
This is mostly done, but `impact` and `target` fields also appear in the nodes and relatednodes.  How hard would it be to remove them there as well?

**Comment by gbinal** [comment]
This is done.  I'll close once I have a chance to confirm.
