### ISSUE TITLE
add 6 new tag scans to production 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#882]
- <meta name='keywords' - Decent adoption and useful content indicators
- <meta property="og:image" - Important component of OG implementation
- <meta property="og:type" - Important component of OG implementation
- `<meta property="og:url"` - Important component of OG implementation
- `<html  lang=` - Important data for multilingual content analysis
- `<link hreflang=` - Important data for multilingual content analysis

**Comment by gbinal** [comment]
Field IDs and location: 

keywords - after description, before og_title
og_image - after og_article_modified
og_type - after og_image
og_url - after og_type
language  - after canonical_link
language_link - after language_link

**Comment by akuny** [comment]
These changes are deployed and the scanner will re-run tonight for a fresh snapshot tomorrow 3/28/24.

**Comment by gbinal** [comment]
Wooo!!! on a roll

https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNGIyY2hyNzQ1Zmc5bWZvcDJ2eGEzazA4N2p4cncwOWlubG5ncmd6aSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/YpFgx3k1waPb2w2BI5/giphy.gif

**Comment by gbinal** [comment]
Alas, it looks like something is still keeping the data for these fields from populating the snapshot.  Going to keep this open while that gets ironed out.

**Comment by gbinal** [comment]
thanks for finishing this up.  It looks great!
