### ISSUE TITLE
Remove the JS source map from the query builder.  

### ISSUE THREAD

**Issue by laurenancona** [GSA/site-scanning#9]
Background: 

from https://github.com/18F/site-scanning/issues/924

Some new personnel is handling the false positive verification on our Netsparker scans and they are now re-flagging the source code disclosure from the lodash module. It appears they are unlikely to accept the justification. You may need to remove the JS source maps or figure out how to purge the comments in them during the build process.

Would you mind just not publishing the source map for the site scanning api Federalist site?

https://github.com/18F/site-scanning-query-builder

4/7/20 Update - I just heard back that they were able to push back again in the meantime, so we can hold on worrying about this. It'll likely recur though, so we might as well save ourselves future hassle when we get a chance.

**Comment by gbinal** [comment]
This might not be an issue anymore, as we've since updated lodash.  Let's check first.

**Comment by gbinal** [comment]
Closing this issue while the query builder is on hold.  We can reopen when the time comes.
