### ISSUE TITLE
oddity with language field 

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#914]
1 site has `language=null` when it should be `en` I think

**Comment by gbinal** [comment]
This is for ribd.recreation.gov.  Apparently, it's actually an oddity that the site is doing itself.

**Comment by akuny** [comment]
Here's a screenshot of the DOM after the page has loaded in Chrome:

<img width="141" alt="Screenshot 2024-04-16 at 2 31 18 PM" src="https://github.com/GSA/site-scanning/assets/13356991/e2666821-f611-41ee-b1ac-4c6b0a86bf6d">

**Comment by gbinal** [comment]
Closing in favor of #984
