### ISSUE TITLE
Process dependabot alerts

### ISSUE THREAD

**Issue by gbinal** [GSA/site-scanning#94]
For the ~[query builder](https://github.com/GSA/site-scanning-query-builder) and~ [site scanning engine](https://github.com/GSA/site-scanning-engine).  

Apply updates as called for.

**Comment by gbinal** [comment]
This is worth doing, but is less urgent.  We decided to just focus on #83 and get to this one when we can.

**Comment by wesley-dean-gsa** [comment]
PRs:
https://github.com/GSA/site-scanning-engine/pull/109
https://github.com/GSA/site-scanning-engine/pull/123
https://github.com/GSA/site-scanning-engine/pull/125
https://github.com/GSA/site-scanning-engine/pull/127

**Comment by wesley-dean-gsa** [comment]
At the moment (March 8, 2022), there are no active [Dependabot](https://github.com/GSA/site-scanning-engine/security/dependabot) or [CodeQL alerts](https://github.com/GSA/site-scanning-engine/security/code-scanning).

**Comment by wesley-dean-gsa** [comment]
just pushed a commit that will surface Snyk results through the security tab (where these results were being published)

**Comment by wesley-dean-gsa** [comment]
https://github.com/GSA/site-scanning-engine/pull/166

**Comment by wesley-dean-gsa** [comment]
![Screenshot_2022-03-08_14-41-42](https://user-images.githubusercontent.com/87149725/157312746-4b4e26c9-c8ae-4019-96f8-7f8ab9b8334c.png)

^ this is the result of a Snyk scan running on the branch / PR associated with this issue

**Comment by wesley-dean-gsa** [comment]
(yes, we're aware of these issues and there's a [thread in Slack](https://gsa-tts.slack.com/archives/CJ9JT2F2T/p1646414160601489) to discuss)
