### ISSUE TITLE
Some missing data

### ISSUE THREAD

**Issue by mgifford** [GSA/site-scanning#977]
I created this last week:  
  
[https://docs.google.com/spreadsheets/d/1CsXAzCzghYYwXzGCcrJqrsWpr5f7MbID2Qw6vQvi3sQ/edit#gid=497600811](https://docs.google.com/spreadsheets/d/1CsXAzCzghYYwXzGCcrJqrsWpr5f7MbID2Qw6vQvi3sQ/edit#gid=497600811)  
  
In it:  
[https://www.va.gov/jackson-health-care/](https://www.va.gov/jackson-health-care/)  
 

<table><tbody><tr><td><a href="http://jackson.va.gov">jackson.va.gov</a></td><td><a href="http://va.gov">va.gov</a></td><td>gov</td><td>TRUE</td><td><a href="https://www.va.gov/jackson-health-care/">https://www.va.gov/jackson-health-care/</a></td><td><a href="http://va.gov">va.gov</a></td><td>gov</td><td><a href="http://www.va.gov">www.va.gov</a></td><td>TRUE</td><td>200</td><td>text/html</td><td>TRUE</td><td>FALSE</td><td>Department of Veterans Affairs</td><td>Office of Information and Technology, IT Operations and Services (ITOPS)</td><td>Executive</td><td>FALSE</td><td>["pulse"]</td><td>&nbsp;</td><td>2024-05-04T01:13:47.255Z</td><td>completed</td><td>completed</td><td>completed</td><td>completed</td><td>completed</td><td>completed</td><td>completed</td><td>completed</td><td>TRUE</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>FALSE</td><td>&nbsp;</td><td>TRUE</td><td>{"agency":"VA"}</td><td>["dap.digitalgov.gov","prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com","resource.digital.voice.va.gov","s3-us-gov-west-1.amazonaws.com","www.google-analytics.com","www.googletagmanager.com"]</td><td>6</td><td>[".va.gov","www.va.gov"]</td><td>TRUE</td><td>0.04940820573</td><td>471.2</td><td>["about"]</td><td>&nbsp;</td><td>TRUE</td><td>TRUE</td><td>VA Jackson Health Care | Veterans Affairs</td><td>At G.V. (Sonny) Montgomery VA Medical Center, our health care teams are deeply experienced and guided by the needs of Veterans, their families, and caregivers. Find a health facility near you, and manage your health online. Sign up for community events and updates.</td><td>&nbsp;</td><td>VA Jackson health care | Veterans Affairs</td><td>At G.V. (Sonny) Montgomery VA Medical Center, our health care teams are deeply experienced and guided by the needs of Veterans, their families, and caregivers. Find a health facility near you, and manage your health online. Sign up for community events and updates.</td><td>&nbsp;</td><td>&nbsp;</td><td>/img/styles/3_2_medium_thumbnail/public/2021-04/G.V.%20Sonny%20Montgomery%20Department%20of%20Veterans%20Affairs%20Medical%20Center.jpg</td><td>website</td><td><a href="https://www.va.gov/jackson-health-care/">https://www.va.gov/jackson-health-care/</a></td><td><a href="https://www.va.gov/jackson-health-care/">https://www.va.gov/jackson-health-care/</a></td><td>en</td><td>&nbsp;</td><td>TRUE</td><td>FALSE</td><td>TRUE</td><td><a href="https://www.va.gov/jackson-health-care/">https://www.va.gov/jackson-health-care/</a></td><td>TRUE</td><td>200</td><td>text/html</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>FALSE</td><td>TRUE</td><td><a href="https://www.va.gov/jackson-health-care/">https://www.va.gov/jackson-health-care/</a></td><td>TRUE</td><td>200</td><td>text/html</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>0</td><td>0</td><td>0</td><td>0</td><td>25</td><td>0</td><td>0</td><td>&nbsp;</td><td>0</td><td>25</td><td>&nbsp;</td><td>&nbsp;</td></tr></tbody></table>

  
Is reported not to have a link to an accessibility statement, but it is there.

The scraper just reports \["about"\] being there.

Is this accurate, or is there a problem with the script?

**Comment by gbinal** [comment]
Hi @mgifford.  Thanks for reaching out!!!  

We also noticed this happening across a number of va.gov sites and what we realized is the footer on these sites is built in a somewhat less common way.  Our required links scans looks for standard hyperlinks (a la `<a href="URL">text</a>`), but the footers on this site are built with something they call 'live JSON injection'.  The result is a false negative.  

We've done one pass at trying to think about an elegant solution, but didn't have any luck yet, so this remains an open issue but we've also highlighted it with the va.gov team and they may actually shift to a bit more traditional model of coding their footers.  

I'm glad you're diving into our data.  Feel free to reach out to site-scanning@gsa.gov if you ever want to talk about the data more or if you have more feedback on how our data could be improved!
